/* ============================================================
   VDC COMPASS · INTROUKA — DATA + i18n CORE
   Bilingual content. Norwegian is primary; English is for
   international participants (e.g. Martin Fischer).
   Technical VDC terms (VDC, ICE, VIA, PPM, BIM, SPGR, CO/PO …)
   are kept as-is in both languages, by design.
   ============================================================ */

/* ---- i18n core ----
   LANG          : "no" | "en"
   L(no,en)      : inline picker for UI chrome strings
   T(no,en)      : marks a translatable leaf inside data objects
   locVal(v)     : deep-resolves a *_SRC tree into the active language,
                   leaving structural fields (colors, keys, board ids) intact.
*/
let LANG = "no";
function L(no, en){ return LANG === "en" ? en : no; }
function T(no, en){ return {__t:1, no:no, en:en}; }
function locVal(v){
  if(v && v.__t) return (v[LANG] !== undefined ? v[LANG] : v.no);
  if(Array.isArray(v)) return v.map(locVal);
  if(v && typeof v === "object"){ const o={}; for(const k in v) o[k]=locVal(v[k]); return o; }
  return v;
}

const ANAT_SRC=[
  {cls:"p1",tag:T("Input · ca. 60 min","Input · ~60 min"),ic:"present",
    h:T("Martin Fischer setter standarden","Martin Fischer sets the standard"),
    p:T("Plenum for alle 60: bakgrunn, tankesett og hensikt – hvorfor VDC er bygd slik, og hva elementet løser.","Plenary for all 60: the background, mindset and purpose — why VDC is built this way, and what the element solves.")},
  {cls:"p2",tag:T("Trening · 60 min","Practice · 60 min"),ic:"group",
    h:T("Arbeidsgruppene trener","The work groups practice"),
    p:T("Grupper på 5 jobber praktisk med sin valgte kontekst. Arbeidsformen varierer per sesjon – fra 1–2–4–Alle til spill og simulering.","Groups of 5 work hands-on with their chosen context. The working method changes each session — from 1–2–4–All to games and simulation.")},
  {cls:"p3",tag:T("Refleksjon · 60 min","Reflection · 60 min"),ic:"chat",
    h:T("Mentorteamet reflekterer","The mentor team reflects"),
    p:T("De fire gruppene deler og reflekterer på tvers – også her med vekslende form: snøball, gallery walk, World Café og mer.","The four groups share and reflect across teams — again with a varied format: snowball, gallery walk, World Café and more.")}
];

/* ---- generic context library (students choose, or bring own case) ---- */
const KONTEKST_SRC=[
  {t:T("Næringsbygg under rehabilitering","Commercial building being refurbished"),sektor:T("Bygg","Building"),fase:T("Prosjektering","Design"),
    s:T("Et eldre kontorbygg skal oppgraderes mens deler er i drift. Stramt budsjett, høye miljøkrav (BREEAM) og mange tekniske fag.","An older office building is upgraded while parts stay in use. Tight budget, high environmental targets (BREEAM) and many engineering disciplines."),
    c:T("Sene tverrfaglige avklaringer gir fare for omarbeiding og budsjettsprekk.","Late cross-disciplinary decisions risk rework and budget overruns.")},
  {t:T("Boligprosjekt med gjentakende enheter","Housing project with repeating units"),sektor:T("Bygg","Building"),fase:T("Byggefase","Construction"),
    s:T("Boligblokk med mange like leiligheter og mange underentreprenører som skal koordineres.","An apartment block with many identical units and many subcontractors to coordinate."),
    c:T("Ujevn flyt og venting mellom fag presser fremdrift og kvalitet.","Uneven flow and waiting between trades squeeze both schedule and quality.")},
  {t:T("Veiprosjekt med krevende grunnforhold","Road project with difficult ground conditions"),sektor:T("Anlegg","Civil"),fase:T("Bygging","Construction"),
    s:T("Veistrekning med vanskelig grunn, naboer og trafikk som skal opprettholdes underveis.","A road section with difficult ground, neighbors, and traffic that must keep flowing."),
    c:T("Stor usikkerhet og variabilitet gjør fremdriften uforutsigbar.","High uncertainty and variability make progress unpredictable.")},
  {t:T("Baneprosjekt med mange grensesnitt","Rail project with many interfaces"),sektor:T("Infrastruktur","Infrastructure"),fase:T("Prosjektering → bygging","Design → construction"),
    s:T("Jernbane-/tunnelprosjekt med signal, spor og sikkerhet, og en offentlig byggherre.","A rail/tunnel project with signaling, track and safety, and a public-sector client."),
    c:T("Sterke gjensidige avhengigheter og sene beslutninger skaper flaskehalser.","Strong mutual dependencies and late decisions create bottlenecks.")},
  {t:T("Industrianlegg med samtidig design og bygging","Industrial plant designed and built at once"),sektor:T("Industri","Industry"),fase:T("Gjennomføring","Delivery"),
    s:T("Et prosessanlegg der teknologi utvikles mens bygget reises (jf. FREYR Giga Arctic).","A process plant where the technology is developed while the building goes up (cf. FREYR Giga Arctic)."),
    c:T("Ekstrem usikkerhet krever raske, pålitelige beslutninger på sviktende grunnlag.","Extreme uncertainty demands fast, reliable decisions on incomplete information.")},
  {t:T("Komplekst formålsbygg (f.eks. sykehus)","Complex special-purpose building (e.g. hospital)"),sektor:T("Bygg","Building"),fase:T("Prosjektering","Design"),
    s:T("Bygg med svært mange tekniske fag og brukere som skal involveres.","A building with many engineering disciplines and end users who must be involved."),
    c:T("Kollisjoner, endringer og koordinering truer både kostnad og kvalitet.","Clashes, changes and coordination threaten both cost and quality.")},
  {t:T("Ferdigstillelse og overlevering til drift","Completion and handover to operations"),sektor:T("Alle sektorer","All sectors"),fase:T("Ferdigstillelse / drift","Completion / operations"),
    s:T("Systematisk ferdigstillelse og overlevering av et prosjekt til driftsorganisasjonen.","Systematic completion and handover of a project to the operations organization."),
    c:T("Informasjon faller mellom faser; mangelfull dokumentasjon gir driftsproblemer.","Information falls between phases; poor documentation causes operational problems.")}
];

/* ---- the 6 sessions ---- */
const SESS_SRC=[
{ no:1,key:"intro",color:"#1c1f26",accent:"#00509E",day:T("Tirsdag 04.08 · Dag 1","Tuesday Aug 4 · Day 1"),time:"09:00–12:00",
  tema:T("VDC Intro – det store bildet","VDC Intro – the big picture"),el:T("Plenum: «VDC as a Whole» (Martin Fischer)","Plenary: “VDC as a Whole” (Martin Fischer)"),
  goal:T("Forstå at valget av suksesskriterier («performance objectives») avgjør hvilke fag som må være på teamet – og at et godt bygg krever at konflikter mellom konkurrerende mål løses samtidig og integrert, på et godt informasjonsgrunnlag.","Understand that the choice of success criteria (performance objectives) decides which disciplines belong on the team — and that a good building requires conflicts between competing objectives to be solved concurrently and in an integrated way, on a solid base of information."),
  fischer:[
    T("Uten en tydelig suksessdefinisjon («performance objectives») er det umulig å skape et godt prosjekt.","Without a clear definition of success (performance objectives), you cannot create a good project."),
    T("Uten at noen står opp for et mål, blir det ikke nådd – hvert mål trenger en eier.","Unless someone owns an objective, it won't be met — every objective needs an owner."),
    T("Uten å løse konflikter mellom konkurrerende mål samtidig og integrert (alle fag samtidig), tar det for lang tid å finne et godt design – eller tids-/budsjettpress tvinger fram en dårligere løsning.","If you don't resolve conflicts between competing objectives concurrently and integrated (all disciplines at once), finding a good design takes too long — or time and budget pressure forces a worse one."),
    T("Uten visualiseringer bygd på god, integrert informasjon fra alle fag, klarer ikke teamet å samarbeide effektivt om designet.","Without visualizations built on good, integrated information from every discipline, the team can't collaborate effectively on the design."),
    T("Uten å styre «produksjonen» av informasjon, beslutninger og fysisk arbeid blir bygget for dyrt, tar for lang tid – og når neppe målene.","Without managing the “production” of information, decisions and physical work, the building costs too much, takes too long — and likely misses its objectives."),
    T("AI skjerper behovet for å være tydelig på hva mennesker vs. maskiner skal gjøre i prosessen.","AI raises the stakes for being explicit about what humans vs. machines should do in the process.")],
  connect:T("Startpunktet: gruppa velger sin kontekst og definerer 2–3 forbedringsmål – hvert med en tydelig eier – som bæres gjennom alle de neste sesjonene.","The starting point: the group picks its context and defines 2–3 improvement objectives — each with a clear owner — carried through every session that follows."),
  oppgaver:[
    {n:1,type:"refleksjon",q:T("Hvorfor leverer prosjekter som ligner deres kontekst ofte ikke godt nok på budsjett, tid, kvalitet eller miljø?","Why do projects like your context often fall short on budget, time, quality or environment?"),
      how:T("Idémyldre i 5 min. Skriv én årsak per gul lapp og heng dem på flippover. Grupper deretter like årsaker.","Brainstorm for 5 min. Write one cause per yellow note and post them on the flip chart. Then cluster similar causes."),
      svar:[T("Uklar prosjektledelse og manglende usikkerhetsstyring","Unclear project leadership and weak management of uncertainty"),T("Utydelige kravspesifikasjoner","Vague requirements"),T("Lite standardisering, erfaringsoverføring og gjentakelse","Little standardization, knowledge transfer or repetition"),T("Sen tverrfaglig avklaring → omarbeiding","Late cross-disciplinary decisions → rework")],
      tool:{k:"free",title:T("Årsakstavle","Causes board"),prompt:T("Skriv én årsak per lapp. Dra like årsaker sammen i klynger. Slå på stem-modus og prikk de viktigste.","One cause per note. Drag similar causes into clusters. Turn on vote mode and dot the most important ones."),vote:true}},
    {n:2,type:"praktisk",q:T("Hvilke 2–3 forbedringsmål bør konteksten ha, og hvilke VDC-tiltak kan bidra til hvert mål?","Which 2–3 improvement objectives should the context have, and which VDC actions support each one?"),
      how:T("Skriv hvert forbedringsmål (f.eks. «levere på budsjett», «−20 % tid», «−20 % karbon») på en grønn lapp øverst på arket. Heng konkrete tiltak (blå lapper) under riktig mål.","Write each improvement objective (e.g. “deliver on budget”, “−20% time”, “−20% carbon”) on a green note at the top. Place concrete actions (blue notes) under the objective they support."),
      svar:[T("Standardisering og erfaringsoverføring via BIM og ICE/Big Room","Standardization and knowledge transfer through BIM and ICE/Big Room"),T("Kravspesifikasjon, sjekklister og evalueringsskjema","Requirements, checklists and evaluation forms"),T("Begynne å måle; bruke Choosing by Advantage for valg","Start measuring; use Choosing by Advantage for decisions")],
      tool:{k:"cols",title:T("Forbedringsmål → tiltak","Improvement objectives → actions"),addCol:true,prompt:T("Døp hver kolonne til ett forbedringsmål (f.eks. «−20 % tid»). Legg konkrete VDC-tiltak som kort under målet de bidrar til.","Name each column after one improvement objective (e.g. “−20% time”). Add concrete VDC actions as cards under the objective they support."),cols:[{t:T("Forbedringsmål 1","Improvement objective 1"),color:"#2e7d57"},{t:T("Forbedringsmål 2","Improvement objective 2"),color:"#2e7d57"},{t:T("Forbedringsmål 3","Improvement objective 3"),color:"#2e7d57"}],carry:"goals"}},
    {n:3,type:"praktisk",q:T("Hvilket VDC-element hører hvert tiltak til, og hva er elementets rolle?","Which VDC element does each action belong to, and what is that element's role?"),
      how:T("Lag fire kolonner: VIA · ICE · PPM · Samspill. Flytt tiltakslappene fra oppgave 2 til riktig kolonne, og skriv én setning om rollen til hvert element.","Make four columns: VIA · ICE · PPM · Collaboration. Move the action notes from task 2 into the right column, and write one sentence on each element's role."),
      svar:[T("VIA: informasjonshåndtering og -flyt; kommunisere hva som skal bygges (BIM)","VIA: managing information and its flow; communicating what will be built (BIM)"),T("ICE: arena for tverrfaglig avklaring og erfaringsdeling (Big Room)","ICE: the arena for cross-disciplinary decisions and shared learning (Big Room)"),T("PPM: måle definerte parametere og finne forbedringspotensial (økonomi, HMS, kvalitet, miljø)","PPM: measure defined parameters and find improvement potential (cost, HSE, quality, environment)"),T("Samspill: BIM som verktøy i ICE for visualisering og samhandling","Collaboration: BIM as a tool inside ICE for visualization and teamwork")],
      tool:{k:"cols",title:T("VDC-sortering","VDC sorting"),fixed:true,fromBoard:"s1-o2",fromLabel:T("Hent tiltakene fra oppgave 2","Pull the actions from task 2"),prompt:T("Trykk «Hent tiltakene fra oppgave 2» – da dukker de opp i feltet «Til sortering». Dra hvert tiltak inn i VDC-elementet det hører til. Skriv én setning om hva elementet gjør øverst i kolonnen.","Click “Pull the actions from task 2” — they appear in the “To sort” tray. Drag each action into the VDC element it belongs to. Write one sentence on what the element does at the top of the column."),cols:[{t:T("VIA","VIA"),color:"#5d3fa3"},{t:T("ICE","ICE"),color:"#00509E"},{t:T("PPM","PPM"),color:"#0e7d73"},{t:T("Samspill","Collaboration"),color:"#b5610a"}]}},
    {n:4,type:"refleksjon",q:T("Hvilke 2–3 utfordringer kan oppstå når VDC skal innføres i konteksten, og hvordan vil dere møte dem?","Which 2–3 challenges could arise when introducing VDC in the context, and how will you handle them?"),
      how:T("Diskuter i gruppa. Noter utfordring + tiltak parvis på et ark.","Discuss in the group. Note each challenge with its action, side by side."),
      svar:[T("Må forankres i prosjektledelsen","Must be anchored with project leadership"),T("Brukerne må støtte VDC; ufarliggjøre og motivere","Users must back VDC; reassure and motivate them"),T("Mange kan lite om VDC – informere om formålet og lære bort konseptet","Many know little about VDC — explain the purpose and teach the concept")],
      tool:{k:"cols",title:T("Utfordring → tiltak","Challenge → action"),prompt:T("Skriv hver utfordring som et kort til venstre, og tiltaket dere vil møte den med rett overfor til høyre.","Write each challenge as a card on the left, and the action you'll meet it with directly opposite on the right."),cols:[{t:T("Utfordring","Challenge"),color:"#8C1515"},{t:T("Slik møter vi den","How we handle it"),color:"#2e7d57"}]}},
    {n:5,type:"refleksjon",q:T("(Valgfri) Hvor sikre er dere – på en skala 1–5 – på at forslagene vil oppfylle kundens og prosjektets mål?","(Optional) How confident are you — on a 1–5 scale — that the proposals will meet the client's and project's objectives?"),
      how:T("Hver person setter en verdi i stillhet; begrunn deretter de største forskjellene i gruppa.","Everyone picks a value in silence; then discuss the biggest differences as a group."),
      svar:[T("Diskuter hva som må på plass for å øke sikkerheten.","Discuss what has to be in place to raise the confidence.")],
      tool:{k:"scale",title:T("Sikkerhetsmåler","Confidence meter"),max:5,prompt:T("Alle stemmer i stillhet (1 = usikker, 5 = svært sikker). Snakk deretter om de største forskjellene.","Everyone votes in silence (1 = unsure, 5 = very confident). Then talk through the biggest gaps.")}}
  ],
  reflect:[T("Hvordan var årsakene like/ulike på tvers av kontekstene?","How were the causes alike or different across the contexts?"),T("Hvilket element tror dere blir vanskeligst å få til i praksis?","Which element do you think will be hardest to pull off in practice?"),T("Hvor ser dere den sterkeste koblingen mellom to elementer?","Where do you see the strongest link between two elements?")],
  facilitate:[T("Sikre at alle fire elementer kobles til CO/PO.","Make sure all four elements connect back to CO/PO."),T("Få fram «helheten > delene» med konkrete eksempler.","Bring out “the whole > the parts” with concrete examples."),T("Løft fram at VDC er en metode, ikke teknologi.","Stress that VDC is a method, not a technology.")],
  awareness:T("Valget av suksesskriterier avgjør hvem som må være på teamet – og uten en eier som står opp for hvert mål, blir det ikke nådd.","The choice of success criteria decides who belongs on the team — and without an owner standing up for each objective, it won't be met."),
  material:[T("Kontekstbibliotek / egen case","Context library / your own case"),T("VDC-kart-mal","VDC map template"),T("Forkursets rammeverksdiagram","Framework diagram from the pre-course")],
  mentorTips:[T("Følg med på «verktøy-fellen»: vri dem tilbake til sammenhengen og målene.","Watch for the “tool trap”: steer them back to the context and the objectives."),T("Pass på at de forankrer i CO/PO før de diskuterer elementer.","Make sure they anchor in CO/PO before debating elements."),T("SPGR-blikk: hvem dominerer (Kontroll), hvem er passiv (Avhengighet)?","SPGR lens: who dominates (Control), who's passive (Dependence)?"),T("Tidsboks presentasjonene hardt – sett tonen for hele uka.","Time-box the presentations hard — set the tone for the whole week.")],
  takeaway:T("Tydelige mål med eiere, og konflikter løst samtidig og integrert på et godt informasjonsgrunnlag, er det som skaper et bygg som faktisk når målene.","Clear objectives with owners, and conflicts solved concurrently and integrated on a solid base of information — that's what creates a building that actually meets its goals.") },

{ no:2,key:"metrics",color:"#8C1515",accent:"#8C1515",day:T("Tirsdag 04.08 · Dag 1","Tuesday Aug 4 · Day 1"),time:"13:00–16:00",
  tema:T("Målinger (Metrics)","Metrics"),el:T("Plenum: «Metrics / Målstyring» (Martin Fischer)","Plenary: “Metrics” (Martin Fischer)"),
  goal:T("Kunne definere mål for tre tidshorisonter – kundemål, prosjektmål og produksjonsmål – som henger sammen, og måle de kontrollerbare handlingene som avgjør kostnaden ved å nå dem, slik at «alle lager samme film».","Be able to define objectives for three horizons — Client Objectives, Project Objectives and Production Objectives — that connect, and to measure the controllable actions that drive the cost of reaching them, so that “everyone makes the same movie.”"),
  fischer:[
    T("«Hemmeligheten bak en god film er å sørge for at alle lager samme film.» Vage OKR-er og KPI-er er for upresise til å sikre det.","“The secret to a good movie is making sure everyone makes the same movie.” Vague OKRs and KPIs are too imprecise to ensure that."),
    T("Kundemål (langsiktig): hvordan skal bygget prestere for brukere, drift, eier, finansiør og naboer?","Client Objectives (long-term): how should the building perform for users, operations, the owner, the financier and the neighbors?"),
    T("Prosjektmål (ved overlevering): HMS, kvalitet, fremdrift, kost og bærekraft.","Project Objectives (at handover): HSE, quality, schedule, cost and sustainability."),
    T("Produksjonsmål: feedback-løkker målt minst én gang i uka, som viser om prosjektet er på rett vei.","Production Objectives: feedback loops measured at least weekly, showing whether the project is on track."),
    T("De tre nivåene må være på linje – og handlingene teamet gjør må også måles, for de bestemmer kostnaden ved å nå målene (kontrollerbare faktorer).","The three levels must be aligned — and the team's actions must be measured too, because they set the cost of reaching the objectives (controllable factors).")],
  connect:T("Bygger direkte på forbedringsmålene gruppa satte i VDC Intro – nå gjøres de målbare.","Builds directly on the improvement objectives set in VDC Intro — now they're made measurable."),
  oppgaver:[
    {n:1,type:"praktisk",q:T("Hvilke av forbedringsmålene hjelper hverandre (synergi)?","Which of the improvement objectives reinforce each other (synergy)?"),
      how:T("Tegn de 2–3 målene som bobler på et storark. Trekk en grønn pil mellom mål som drar i samme retning, og skriv hvorfor på pilen.","Draw the 2–3 objectives as bubbles on a large sheet. Draw a green arrow between objectives that pull the same way, and write why on the arrow."),
      svar:[T("Kortere prosjekterings-/byggetid gjør det lettere å holde budsjett","Shorter design/build time makes it easier to hold the budget"),T("Karbonkutt kan redusere kostnad via mindre transport og materialforbruk","Cutting carbon can cut cost through less transport and material use")],
      tool:{k:"map",title:T("Synergi- og konfliktkart","Synergy & conflict map"),mode:"synergy",prompt:T("Legg hvert forbedringsmål som en boble. Klikk to bobler for å koble dem: grønn pil = drar samme vei (synergi), rød pil = i konflikt (oppgave 2). Velg pilfarge over kartet.","Add each improvement objective as a bubble. Click two bubbles to connect them: green arrow = pull together (synergy), red arrow = conflict (task 2). Choose the arrow color above the map."),boardKey:"s2-map"}},
    {n:2,type:"analyse",q:T("Hvor er målene i konflikt med hverandre?","Where do the objectives conflict?"),
      how:T("Trekk en rød strek mellom mål som motarbeider hverandre, og skriv kort hvorfor.","Draw a red line between objectives that work against each other, and note briefly why."),
      svar:[T("Kortere prosjekteringstid vs. kvalitetssikring og karbon","Shorter design time vs. quality assurance and carbon"),T("Kortere byggetid kan gi mer transport/forsering og økte kostnader","Shorter build time can mean more transport/acceleration and higher cost")],
      tool:{k:"map",title:T("Synergi- og konfliktkart","Synergy & conflict map"),mode:"synergy",prompt:T("Samme kart som oppgave 1. Velg rød pilfarge og koble målene som motarbeider hverandre.","Same map as task 1. Choose the red arrow color and connect the objectives that work against each other."),boardKey:"s2-map",shared:true}},
    {n:3,type:"praktisk",q:T("Hvilken produksjonsmåling, med tallfestet mål, passer for hvert VDC-element (ICE, VIA, PPM)?","Which production metric, with a numeric target, fits each VDC element (ICE, VIA, PPM)?"),
      how:T("Fyll ut måltavla: én rad per element med kolonnene Måling · Enhet · Målsetting.","Fill in the metrics board: one row per element with the columns Metric · Unit · Target."),
      svar:[T("ICE: andel beslutninger tatt i møtet – %, mål > X","ICE: share of decisions made in the meeting — %, target > X"),T("VIA: prosjekteringsfeil funnet tidlig – antall/%, mål","VIA: design errors caught early — count/%, target"),T("PPM: PPU (planlagt produksjon utført) – %, mål > X","PPM: PPC (percent plan complete) — %, target > X")],
      tool:{k:"table",title:T("Måltavle","Metrics board"),prompt:T("Én rad per VDC-element. Fyll inn en konkret produksjonsmåling, enhet og tallfestet målsetting.","One row per VDC element. Enter a concrete production metric, a unit and a numeric target."),cols:[T("Element","Element"),T("Måling","Metric"),T("Enhet","Unit"),T("Målsetting","Target")],rows:[["ICE","","",""],["VIA","","",""],["PPM","","",""]],lockCol0:true}},
    {n:4,type:"analyse",q:T("Hvordan bidrar én av produksjonsmålingene til at dere når ett bestemt forbedringsmål?","How does one of the production metrics help you reach one specific improvement objective?"),
      how:T("Velg ett mål og én måling. Skriv sammenhengen i én klar setning.","Pick one objective and one metric. Write the link in a single clear sentence."),
      svar:[T("Ukentlige PPU-avstemninger gir tidlig varsel om forsinkelse → tiltak → treffer fremdriftsmålet","Weekly PPC reviews flag delay early → action → hit the schedule objective")]},
    {n:5,type:"praktisk",q:T("Hvordan henger målkjeden sammen – fra prosjektmål helt ned til det dere kan styre?","How does the chain connect — from Project Objectives all the way down to what you can control?"),
      how:T("Lag tre rader med lapper: Prosjektmål (øverst) → Produksjonsmåling (midten) → Kontrollerbar faktor (nederst). Trekk streker mellom lappene som hører sammen, så hele kjeden vises.","Make three rows of notes: Project Objective (top) → Production metric (middle) → Controllable factor (bottom). Draw lines between the notes that belong together, so the whole chain shows."),
      svar:[T("For hver produksjonsmåling: definer 1–2 kontrollerbare faktorer","For each production metric: define 1–2 controllable factors"),T("Kjeden viser at en daglig handling kan spores opp til kundens mål","The chain shows how a daily action traces up to the client's objective")],
      tool:{k:"map",title:T("Målkjeden","The objective chain"),mode:"chain",bands:[{t:T("Prosjektmål","Project Objective"),color:"#8C1515"},{t:T("Produksjonsmåling","Production metric"),color:"#00509E"},{t:T("Kontrollerbar faktor","Controllable factor"),color:"#2e7d57"}],prompt:T("Legg kort i riktig bånd: prosjektmål øverst, produksjonsmåling i midten, kontrollerbar faktor nederst. Klikk to kort for å trekke en strek mellom dem og vise hele kjeden.","Place cards in the right band: Project Objective on top, production metric in the middle, controllable factor at the bottom. Click two cards to draw a line and show the full chain.")}}
  ],
  reflect:[T("Er målingene faktisk målbare – eller fortsatt ønsker?","Are the metrics actually measurable — or still wishes?"),T("Henger kontrollerbare faktorer logisk sammen med målingene?","Do the controllable factors connect logically to the metrics?"),T("Hvilke mål ville skapt mest felles retning?","Which objectives would create the most shared direction?")],
  facilitate:[T("Sikre skillet produksjonsmåling (utfall) vs. kontrollerbar faktor (handling).","Hold the distinction: production metric (outcome) vs. controllable factor (action)."),T("Utfordre vage formuleringer – be om tall og enhet.","Challenge vague wording — ask for a number and a unit."),T("Knytt kjeden tilbake til kundens hvorfor (CO).","Tie the chain back to the client's why (CO).")],
  awareness:T("Vage mål gjør at folk lager hver sin film. Tre mål-nivåer som henger sammen, med ukentlige feedback-løkker, gir hele teamet samme film.","Vague objectives make everyone shoot a different movie. Three connected objective levels, with weekly feedback loops, get the whole team making the same one."),
  material:[T("Forbedringsmål fra VDC Intro","Improvement objectives from VDC Intro"),T("Måltavle-mal","Metrics board template"),T("Metrics-pyramide fra forkurset","Metrics pyramid from the pre-course")],
  mentorTips:[T("Vanligste feil er vage mål – be alltid om tall og enhet.","The most common mistake is vague objectives — always ask for a number and a unit."),T("Hold fast på skillet utfall vs. handling.","Hold firm on the outcome vs. action distinction."),T("La gruppene utfordre hverandres målkjeder (Opposisjon).","Let groups challenge each other's chains (Opposition)."),T("Koble til den enkeltes eget prosjekt: «hva er DIN kundes hvorfor?»","Connect to each person's own project: “what is YOUR client's why?”")],
  takeaway:T("Få alle til å lage samme film: kundemål, prosjektmål og produksjonsmål på linje – og mål de kontrollerbare handlingene.","Get everyone making the same movie: Client, Project and Production Objectives aligned — and measure the controllable actions.") },

{ no:3,key:"ice",color:"#00509E",accent:"#00509E",day:T("Onsdag 05.08 · Dag 2","Wednesday Aug 5 · Day 2"),time:"09:00–12:00",
  tema:T("ICE – beslutninger i sanntid","ICE – real-time decisions"),el:T("Plenum: «ICE» (Martin Fischer)","Plenary: “ICE” (Martin Fischer)"),
  goal:T("Kunne kjenne igjen gjensidig avhengig (reciprocal) arbeidsflyt, og planlegge og kjøre en ICE-sesjon som korter ned respons- og beslutningslatens.","Be able to recognize reciprocal (interdependent) workflow, and to plan and run an ICE session that cuts response and decision latency."),
  fischer:[
    T("Tre typer arbeidsflyt – pooled (uavhengig), sekvensiell (avhengig) og gjensidig (reciprocal) – krever hver sin koordineringsmekanisme.","Three types of workflow — pooled (independent), sequential (dependent) and reciprocal (interdependent) — each need a different coordination mechanism."),
    T("Gjensidige arbeidsflyt er spesielt vanskelige; håndtert sekvensielt og oppstykket (hvert fag for seg) fører de sjelden til et godt prosjekt.","Reciprocal workflows are the hard ones; handled sequentially and in silos (each discipline alone), they rarely lead to a good project."),
    T("Å løse gjensidige problemer samtidig, med et integrert team av de relevante deltakerne, har størst sjanse til å finne en god løsning.","Solving reciprocal problems concurrently, with an integrated team of the relevant participants, has the best shot at a good solution."),
    T("Respons-latens og beslutnings-latens er to nøkkelmålinger – de skal være så korte som mulig.","Response latency and decision latency are two key metrics — keep them as short as possible."),
    T("ICE-sesjoner (fra 45-min enkeltsak til flerdagers og co-location) er det beste verktøyet vi kjenner for å korte ned latensen.","ICE sessions (from a 45-min single issue to multi-day and co-location) are the best tool we know to cut that latency.")],
  connect:T("Tar en konkret, gjensidig problemstilling fra konteksten og planlegger og kjører en ICE-sesjon for den. Bygger opp mot den fulle 1-times ICE-simuleringen tirsdag kveld.","Takes a concrete reciprocal problem from the context and plans and runs an ICE session for it. Builds toward the full one-hour ICE simulation on Tuesday evening."),
  oppgaver:[
    {n:1,type:"analyse",q:T("Hvilken gjensidig avhengig problemstilling fra konteksten egner seg for en ICE-sesjon?","Which reciprocal problem from the context is a good fit for an ICE session?"),
      how:T("Velg ett tema der minst to fag må løse noe sammen. Skriv det som ett tydelig beslutningsspørsmål: «Vi må bestemme …».","Pick one issue where at least two disciplines must solve something together. Write it as one clear decision question: “We need to decide …”."),
      svar:[T("F.eks. plassering av bygg på trang tomt, eller et energimål som krever ARK + RIV samtidig","E.g. siting the building on a tight plot, or an energy target that needs ARK + RIV at once"),T("Velg noe konkret nok til å kunne besluttes i løpet av en kort økt","Pick something concrete enough to decide within a short session")]},
    {n:2,type:"praktisk",q:T("Hvordan ser en god ICE-sesjon ut for denne problemstillingen?","What does a good ICE session look like for this problem?"),
      how:T("Planlegg på et A3-ark: a) skriv hvem som inviteres (rolle på lapper, plasser dem rundt «bordet»), b) hvilket underlag må være klart, c) agenda i 3–4 punkter.","Plan on an A3 sheet: a) who's invited (roles on notes, placed around the “table”), b) what inputs must be ready, c) a 3–4 point agenda."),
      svar:[T("a) ARK, RIV/RIB, byggherre – fordi de eier konsekvensene","a) ARK, RIV/RIB, Client — because they own the consequences"),T("b) 2–3 konseptforslag, oppdatert modell, kostnadsbilde","b) 2–3 concept options, an updated model, a cost picture"),T("c) hensikt → gjennomgang → beslutning → ansvar videre","c) purpose → review → decision → who-does-what next")],
      tool:{k:"ice",title:T("ICE-planlegger","ICE planner"),prompt:T("Dra inn fagrollene som må sitte rundt ICE-bordet. List opp underlaget som må være klart, og sett en agenda på 3–4 punkter.","Drag in the disciplines that must sit around the ICE table. List the inputs that must be ready, and set a 3–4 point agenda.")}},
    {n:3,type:"praktisk",q:T("Klarer dere å ta beslutningen sammen i sanntid? Kjør en mini ICE-sesjon.","Can you make the decision together in real time? Run a mini ICE session."),
      how:T("Fordel fagrollene fra oppgave 2 i gruppa. Tidtaker styrer. Kjør sesjonen og ta den faktiske beslutningen på 15 minutter. Skriv ned beslutningen og hvem som gjør hva videre.","Assign the disciplines from task 2 within the group. The timekeeper runs the clock. Run the session and make the actual decision in 15 minutes. Write down the decision and who does what next."),
      svar:[T("Poenget er å oppleve sanntidsbeslutning på et gjensidig problem","The point is to experience a real-time decision on a reciprocal problem"),T("Dette er en forsmak på den fulle 1-times ICE-simuleringen tirsdag kveld","This is a preview of the full one-hour ICE simulation on Tuesday evening")],
      tool:{k:"icesim",title:T("ICE-simulering","ICE simulation"),fromBoard:"s3-o2",prompt:T("Kjør en full ICE-sesjon i sanntid: fordel rollene (hentes fra planleggeren i oppgave 2), gå gjennom de fem fasene med klokka, og ta beslutningen sammen mens alle fag er i rommet. Til slutt ser dere hvor mye tid ICE sparte mot en sekvensiell prosess.","Run a full ICE session in real time: assign the roles (pulled from the planner in task 2), step through the five phases on the clock, and make the decision together while every discipline is in the room. At the end you see how much time ICE saved versus a sequential process.")}},
    {n:4,type:"analyse",q:T("Hvordan kan dere måle om ICE-sesjonen var vellykket – under, rett etter, og en måned etter?","How can you measure whether the ICE session succeeded — during, right after, and one month later?"),
      how:T("Skriv 1–2 tallfestede produksjonsmålinger for hvert av de tre tidspunktene.","Write 1–2 numeric production metrics for each of the three points in time."),
      svar:[T("Under: underlag på plass / forberedt (> 4,5); riktige deltakere til stede (> 90 %)","During: inputs ready / prepared (> 4.5); right people present (> 90%)"),T("Rett etter: underlag godt nok til beslutning? (> 90 %); ga møtet verdi? (1–5, > 4,5)","Right after: inputs good enough to decide? (> 90%); did the meeting add value? (1–5, > 4.5)"),T("En måned etter: antall omgjorte beslutninger (mål: lavt)","One month later: number of reversed decisions (target: low)")],
      tool:{k:"table",title:T("ICE-målinger","ICE metrics"),prompt:T("Skriv 1–2 tallfestede produksjonsmålinger for hvert tidspunkt.","Write 1–2 numeric production metrics for each point in time."),cols:[T("Tidspunkt","When"),T("Måling","Metric"),T("Målsetting","Target")],rows:[[T("Under","During"),"",""],[T("Rett etter","Right after"),"",""],[T("En måned etter","One month later"),"",""]],lockCol0:true}}
  ],
  reflect:[T("Hva gjorde beslutningene raske og trygge?","What made the decisions fast and confident?"),T("Hva ville stoppet flyten i en ekte økt?","What would have stalled the flow in a real session?"),T("Hvor mye ventetid (latens) sparte dere mot en sekvensiell prosess?","How much waiting (latency) did you save versus a sequential process?")],
  facilitate:[T("Hold fokus på de gjensidige problemene – ikke det sekvensielle.","Keep the focus on reciprocal problems — not sequential ones."),T("Fremhev forberedelse og fasilitering som forskjellen på ICE og statusmøte.","Highlight preparation and facilitation as what separates ICE from a status meeting."),T("Knytt til Aurora 2: gjensidig arbeid ga målbart bedre resultat.","Connect to Aurora 2: reciprocal work produced measurably better results.")],
  awareness:T("Gjensidige problemer kan ikke løses fag-for-fag. ICE samler fagene samtidig og kapper respons- og beslutningslatensen.","Reciprocal problems can't be solved discipline-by-discipline. ICE brings the disciplines together at once and cuts response and decision latency."),
  material:[T("Valgt kontekst","Chosen context"),T("ICE-planmal","ICE plan template"),T("FREYR ICE-målinger som eksempel","FREYR ICE metrics as an example"),T("Rollekort (fag/beslutningstakere)","Role cards (disciplines / decision-makers)")],
  mentorTips:[T("Sørg for at de planlegger for gjensidige problemer – ikke noe sekvensielt.","Make sure they plan for reciprocal problems — nothing sequential."),T("I live-ICE: hold tempo, tving fram beslutninger.","In the live ICE: keep the pace, force decisions."),T("Observer hvem som tar fasilitatorrollen (SPGR: Kontroll).","Notice who takes the facilitator role (SPGR: Control)."),T("Knytt til kveldens ICE-simulering og til VIA (info som grunnlag).","Connect to the evening ICE simulation and to VIA (information as the basis).")],
  takeaway:T("ICE er det beste verktøyet vi har for gjensidig arbeidsflyt – det korter respons- og beslutningslatens fra uker til timer.","ICE is the best tool we have for reciprocal workflow — it cuts response and decision latency from weeks to hours.") },

{ no:4,key:"ppm-p",color:"#0e7d73",accent:"#0e7d73",day:T("Onsdag 05.08 · Dag 2","Wednesday Aug 5 · Day 2"),time:"13:00–16:00",
  tema:T("PPM – prosessmapping","PPM – process mapping"),el:T("Plenum: «PPM Prosessmapping» (Martin Fischer)","Plenary: “PPM Process Mapping” (Martin Fischer)"),
  goal:T("Kunne kartlegge prosjektets produksjonsprosess med steg, køer og lager, sette policyer for hvordan aktivitetene henger sammen, og finne flaskehalsen som forbedring skal rettes mot.","Be able to map the project's production process with steps, queues and inventory, set policies for how the activities connect, and find the bottleneck that improvement should target."),
  fischer:[
    T("«Klarer du ikke å kartlegge prosessen din, vet du ikke hva du driver med.»","“If you can't map your process, you don't know what you're doing.”"),
    T("Et prosjekt er et produksjonssystem – satt sammen av produksjonsprosesser OG produksjonspolicyer.","A project is a production system — made up of production processes AND production policies."),
    T("Det viktigste er policyer som styrer hvordan aktivitetene henger sammen – køer og lager (WIP).","What matters most are the policies that govern how activities connect — queues and inventory (WIP)."),
    T("Den viktigste innsikten fra prosesskart + målinger er å finne flaskehalsen – det er der forbedring skal settes inn.","The key insight from a process map plus metrics is finding the bottleneck — that's where improvement goes."),
    T("Heathrow-armering: ledetid 30→5 dager ved å styre flyten.","Heathrow rebar: lead time cut 30 → 5 days by managing flow.")],
  connect:T("Kartlegger en beslutnings-/produksjonsprosess i konteksten – grunnlaget for variabilitets-sesjonen etterpå.","Maps a decision/production process in the context — the basis for the variability session that follows."),
  oppgaver:[
    {n:1,type:"refleksjon",q:T("Hvor i konteksten oppstår venting (kø), og hvor hoper ferdig arbeid seg opp (lager/WIP)?","Where in the context does waiting (queues) arise, and where does finished work pile up (inventory/WIP)?"),
      how:T("Diskuter og gi to konkrete eksempler på hver. Skriv dem ned før dere bygger kartet.","Discuss and give two concrete examples of each. Write them down before you build the map."),
      svar:[T("Kø: tegninger som venter på godkjenning; svar som venter på avklaring","Queue: drawings waiting for approval; answers waiting for a decision"),T("Lager (WIP): ferdig prosjektert som venter på byggestart","Inventory (WIP): completed design waiting for construction to start")]},
    {n:2,type:"praktisk",q:T("Hvordan ser produksjons-/beslutningsprosessen ut, steg for steg?","What does the production/decision process look like, step by step?"),
      how:T("Bygg prosesskartet fysisk: legg ett kort per steg i svømmebaner (én rad per aktør). Bruk symbolene firkant = arbeidsoppgave, trekant = kø, sylinder = lager, pil = flyt. Flytt på kortene til hele gruppa er enig.","Build the process map physically: one card per step in swimlanes (one row per actor). Use the symbols square = task, triangle = queue, cylinder = inventory, arrow = flow. Move the cards until the whole group agrees."),
      svar:[T("Prosesskart med swimlanes per aktør (byggherre, ARK, RIB, RIV, PL)","A process map with swimlanes per actor (Client, ARK, RIB, RIV, PL)"),T("Kø og lager skal være synlige som egne symboler mellom arbeidsoppgavene","Queues and inventory should be visible as their own symbols between the tasks")],
      tool:{k:"swim",title:T("Prosesskart med svømmebaner","Process map with swimlanes"),prompt:T("Velg et symbol og klikk i en svømmebane for å legge det inn: ▭ arbeidsoppgave · ▷ kø · ⬭ lager (WIP). Dra for å flytte. Hver rad er én aktør.","Pick a symbol and click in a swimlane to place it: ▭ task · ▷ queue · ⬭ inventory (WIP). Drag to move. Each row is one actor."),lanes:[T("Byggherre","Client"),"ARK","RIB","RIV","PL"],boardKey:"proc-map"}},
    {n:3,type:"analyse",q:T("Hvordan kan dere måle prosessen – både hvor effektiv og hvor god den er?","How can you measure the process — both how efficient and how good it is?"),
      how:T("Definer én effektivitetsmåling og én kvalitetsmåling for hele prosessen.","Define one efficiency metric and one quality metric for the whole process."),
      svar:[T("Effektivitet: tid fra bestilling til endelig beslutning (antall dager)","Efficiency: time from request to final decision (number of days)"),T("Kvalitet: står beslutningen seg en måned etter at den er tatt? (ja/nei)","Quality: does the decision still hold a month later? (yes/no)")],
      tool:{k:"table",title:T("Prosessmålinger","Process metrics"),prompt:T("Definer én effektivitets- og én kvalitetsmåling for prosessen.","Define one efficiency and one quality metric for the process."),cols:[T("Type","Type"),T("Måling","Metric"),T("Enhet / mål","Unit / target")],rows:[[T("Effektivitet","Efficiency"),"",""],[T("Kvalitet","Quality"),"",""]],lockCol0:true}},
    {n:4,type:"praktisk",q:T("(Om gruppen har tid) Hvordan kan dere korte ned gjennomløpstiden?","(If the group has time) How can you shorten the lead time?"),
      how:T("Flytt på kortene: fjern en kø, slå sammen steg eller endre rekkefølge. Lag en optimalisert versjon av prosesskartet ved siden av den første.","Move the cards: remove a queue, merge steps or change the order. Build an optimized version of the map next to the first."),
      svar:[T("Færre køer og mindre WIP gir kortere og mer forutsigbar gjennomløpstid","Fewer queues and less WIP give shorter, more predictable lead time")],
      tool:{k:"swim",title:T("Optimalisert prosesskart","Optimized process map"),fromBoard:"proc-map",fromLabel:T("Kopier kartet fra oppgave 2","Copy the map from task 2"),prompt:T("Trykk «Kopier kartet fra oppgave 2» for å starte fra prosessen dere alt har laget. Fjern en kø, slå sammen steg eller endre rekkefølge – og se gjennomløpstiden krympe.","Click “Copy the map from task 2” to start from the process you already built. Remove a queue, merge steps or reorder — and watch the lead time shrink."),lanes:[T("Byggherre","Client"),"ARK","RIB","RIV","PL"],boardKey:"proc-map-opt"}}
  ],
  reflect:[T("Hvor er den største køen eller sløsingen i prosessen?","Where is the biggest queue or waste in the process?"),T("Hvilken kontrollerbar faktor gir størst effekt på flyten?","Which controllable factor has the biggest effect on flow?"),T("Hva ville en kvalitetsmåling avslørt underveis?","What would a quality metric have revealed along the way?")],
  facilitate:[T("Få fram skillet flyteffektivitet vs. ressurseffektivitet.","Bring out the difference between flow efficiency and resource efficiency."),T("Sikre at køer/lager synliggjøres – det er ofte usynlig sløsing.","Make sure queues/inventory are made visible — they're often hidden waste."),T("Knytt målingene konkret til stegene i prosessen.","Tie the metrics concretely to the steps in the process.")],
  awareness:T("Et prosjekt er et produksjonssystem du kan kartlegge og styre. Kartet avslører flaskehalsen – og det er der forbedring skal settes inn.","A project is a production system you can map and manage. The map reveals the bottleneck — and that's where improvement goes."),
  material:[T("Valgt kontekst","Chosen context"),T("Prosesskart-mal med symboler","Process map template with symbols"),T("Heathrow-armeringsprosess som eksempel","Heathrow rebar process as an example")],
  mentorTips:[T("Hjelp dem å se køene – de overser nesten alltid venting og lager.","Help them see the queues — they almost always overlook waiting and inventory."),T("Utfordre «alle må være travle»-tankegangen tidlig.","Challenge the “everyone must be busy” mindset early."),T("Pass på at målinger kobles til konkrete steg, ikke generelle ønsker.","Make sure metrics connect to concrete steps, not general wishes."),T("Bruk armeringseksempelet som mal når en gruppe står fast.","Use the rebar example as a model when a group gets stuck.")],
  takeaway:T("Klarer du ikke å kartlegge prosessen, vet du ikke hva du driver med. Finn flaskehalsen, og forbedre der.","If you can't map your process, you don't know what you're doing. Find the bottleneck, and improve there.") },

{ no:5,key:"ppm-v",color:"#b5610a",accent:"#b5610a",day:T("Torsdag 06.08 · Dag 3","Thursday Aug 6 · Day 3"),time:"09:00–12:00",
  tema:T("PPM – variabilitet","PPM – variability"),el:T("Plenum: «PPM Variabilitet» (Martin Fischer)","Plenary: “PPM Variability” (Martin Fischer)"),
  goal:T("Erfare hvordan variabilitet gjør det umulig å levere både raskt OG billig – og kunne forstå, redusere og buffre variabiliteten i en prosess.","Experience how variability makes it impossible to deliver both fast AND cheap — and be able to understand, reduce and buffer the variability in a process."),
  fischer:[
    T("Variabilitet i varighet, innsats og kvalitet gjør det umulig å nå målene både raskt OG billig.","Variability in duration, effort and quality makes it impossible to hit the objectives both fast AND cheap."),
    T("Kunder forventer suksess raskt og billig – derfor er eneste strategi: forstå variabiliteten, reduser den så mye som mulig, og buffer resten.","Clients expect success fast and cheap — so the only strategy is: understand the variability, reduce it as much as you can, and buffer the rest."),
    T("Selv «gjennomsnittlig» fagytelse gir dårlig systemytelse uten koordinering (Parade of Trades).","Even “average” trade performance gives poor system performance without coordination (Parade of Trades)."),
    T("Buffer, batchstørrelse og pull/push demper eller forsterker variabilitet (jf. Kniberg, Push vs Pull).","Buffer, batch size and pull/push either dampen or amplify variability (cf. Kniberg, Push vs Pull).")],
  connect:T("Tar prosesskartet fra forrige sesjon og reduserer variabiliteten i det.","Takes the process map from the previous session and reduces the variability in it."),
  oppgaver:[
    {n:1,type:"praktisk",q:T("Hva skjer med flyten når variabiliteten er stor? (Terningspillet)","What happens to flow when variability is high? (Dice game)"),
      how:T("Spill terningspillet (Capacity utilization) i gruppa: kjør én runde med høy variabilitet og store batcher. Mål gjennomløp og kølengde, og noter tallene.","Play the dice game (capacity utilization) as a group: run one round with high variability and large batches. Measure throughput and queue length, and note the numbers."),
      svar:[T("Store svingninger gir lange køer og lav, uforutsigbar gjennomstrømning","Big swings produce long queues and low, unpredictable throughput"),T("«Alle travle» betyr ikke at arbeidet flyter","“Everyone busy” doesn't mean the work flows")],
      tool:{k:"dice",title:T("Terningspillet","Dice game"),prompt:T("Fem stasjoner på rad. Hver runde kaster hver stasjon en terning og flytter så mange enheter videre som den klarer – men aldri mer enn det som ligger i køen foran. Kjør runder og se køene bygge seg opp.","Five stations in a row. Each round, every station rolls a die and moves on as many units as it can — but never more than what sits in the queue in front. Run rounds and watch the queues build.")}},
    {n:2,type:"praktisk",q:T("Hva er forskjellen på push og pull? (Lego-flyspillet – eller Kniberg-filmen)","What's the difference between push and pull? (Lego airplane game — or the Kniberg video)"),
      how:T("Alt. A – Lego-flyspillet: bygg fly først i store partier (push), så ett om gangen på trekk (pull). Sammenlign hvor raskt ferdige fly kommer ut og hvor mye «lager» som ligger mellom stasjonene. Alt. B – raskere: se Henrik Kniberg-filmen om Push vs Pull, og reflekter i gruppa etterpå.","Option A — Lego airplane game: build planes first in large batches (push), then one at a time on demand (pull). Compare how fast finished planes come out and how much “inventory” sits between stations. Option B — faster: watch Henrik Kniberg's Push vs Pull video, then reflect as a group."),
      svar:[T("Push fyller systemet med arbeid ingen er klare til å ta imot → køer","Push fills the system with work no one is ready to receive → queues"),T("Pull slipper arbeid løs når neste steg er klart → jevnere flyt, mindre lager","Pull releases work when the next step is ready → smoother flow, less inventory"),T("Film (alternativ): https://www.youtube.com/watch?v=CostXs2p6r0","Video (alternative): https://www.youtube.com/watch?v=CostXs2p6r0")],
      tool:{k:"pushpull",title:T("Push vs Pull","Push vs Pull"),prompt:T("Kjør samme produksjonslinje i PUSH (alle dytter alt de kan) og PULL (slipp bare løs når neste stasjon er klar). Sammenlign ferdige enheter og lager mellom stasjonene.","Run the same production line in PUSH (everyone pushes all they can) and PULL (release only when the next station is ready). Compare finished units and inventory between stations."),video:"https://www.youtube.com/watch?v=CostXs2p6r0"}},
    {n:3,type:"refleksjon",q:T("Hva lærte øvelsene dere – og hvor kjenner dere det igjen i konteksten?","What did the exercises teach you — and where do you recognize it in the context?"),
      how:T("Diskuter: hva skjedde med ventetid og lager da dere gikk fra store til små batcher / fra push til pull? Knytt det til konkrete situasjoner i prosjektet.","Discuss: what happened to waiting and inventory when you went from large to small batches / from push to pull? Tie it to concrete situations in the project."),
      svar:[T("Mindre batch og pull gir kortere ventetid og mindre WIP","Smaller batches and pull give shorter waiting and less WIP"),T("Variabilitet rammer hele systemet, ikke bare ett fag","Variability hits the whole system, not just one discipline")]},
    {n:4,type:"praktisk",q:T("Hvordan kan dere dempe variabiliteten i prosessen fra forrige sesjon?","How can you dampen the variability in the process from the previous session?"),
      how:T("Hent fram prosesskartet fra PPM-prosess. Tegn/legg inn hvor dere vil ha buffer eller endre batchstørrelse, marker endringene, og definer målinger per VDC-element.","Bring up the process map from PPM process mapping. Mark where you'd add a buffer or change batch size, flag the changes, and define metrics per VDC element."),
      svar:[T("Buffer: nok ressurser/underlag klart før ICE-sesjonen; beslutningstaker til stede","Buffer: enough resources/inputs ready before the ICE session; decision-maker present"),T("Tiltak via ICE (standardisert agenda), VIA (alt i én modell), PPM (definert beslutningsprosess)","Actions via ICE (standardized agenda), VIA (everything in one model), PPM (a defined decision process)"),T("Tabell: VDC-element → produksjonsmåling → verdi → målsetting","Table: VDC element → production metric → value → target")],
      tool:{k:"table",title:T("Tiltak mot variabilitet","Actions against variability"),prompt:T("Marker hvor dere vil dempe variabilitet, og koble til VDC-element, måling og målsetting.","Mark where you'll dampen variability, and link it to a VDC element, a metric and a target."),cols:[T("VDC-element","VDC element"),T("Produksjonsmåling","Production metric"),T("Verdi","Value"),T("Målsetting","Target")],rows:[["","","",""],["","","",""],["","","",""]]}}
  ],
  reflect:[T("Hva skjedde da dere reduserte batch eller innførte buffer/pull?","What happened when you reduced batch size or introduced buffer/pull?"),T("Hvor i egne prosjekter kjenner dere igjen denne variabiliteten?","Where in your own projects do you recognize this variability?"),T("Hva er den billigste måten å dempe variabilitet på?","What's the cheapest way to dampen variability?")],
  facilitate:[T("Få fram flyteffektivitet vs. ressurseffektivitet med tall fra spillet.","Bring out flow vs. resource efficiency with numbers from the game."),T("Gjør Littles lov intuitiv (kø, gjennomstrømning, ventetid henger sammen).","Make Little's Law intuitive (queue, throughput and waiting are connected)."),T("Koble opplevelsen til reelle situasjoner i prosjektering/byggeplass.","Connect the experience to real situations in design and on site.")],
  awareness:T("Variabilitet stjeler både tid og penger. Strategien er alltid den samme: forstå → reduser → buffer.","Variability steals both time and money. The strategy is always the same: understand → reduce → buffer."),
  material:[T("Prosesskart fra PPM-prosess","Process map from PPM process mapping"),T("Terningspill (Capacity utilization)","Dice game (capacity utilization)"),T("Kniberg Push/Pull-video","Kniberg Push/Pull video")],
  mentorTips:[T("La spillet snakke – ikke foreles; trekk innsikten ut etterpå.","Let the game speak — don't lecture; pull out the insight afterward."),T("Sørg for at begge runder måles, så forskjellen blir tydelig.","Make sure both rounds are measured, so the difference is clear."),T("Koble følelsen i spillet til ekte erfaring fra prosjekt.","Connect the feel of the game to real project experience."),T("Bruk energien (SPGR: Omsorg) – dette er en leken sesjon.","Use the energy (SPGR: Nurture) — this is a playful session.")],
  takeaway:T("Du kan ikke levere raskt OG billig med høy variabilitet. Forstå den, reduser den – og buffer resten.","You can't deliver fast AND cheap with high variability. Understand it, reduce it — and buffer the rest.") },

{ no:6,key:"via",color:"#5d3fa3",accent:"#5d3fa3",day:T("Torsdag 06.08 · Dag 3","Thursday Aug 6 · Day 3"),time:"13:00–16:00",
  tema:T("VIA – informasjon du kan stole på","VIA – information you can trust"),el:T("Plenum: «VIA» (Martin Fischer)","Plenary: “VIA” (Martin Fischer)"),
  goal:T("Forstå at tillit og godt samarbeid på tvers av fag er nøkkelen til suksess – og hvordan visualisering bygger tillit, mens automatisering korter ned latensen i å få feedback på design- og byggeideer.","Understand that trust and strong cross-disciplinary collaboration are the key to success — and how visualization builds trust, while automation cuts the latency of getting feedback on design and construction ideas."),
  fischer:[
    T("Å bygge tillit og godt samarbeid mellom fagene er nøkkelen til prosjektsuksess.","Building trust and strong collaboration between disciplines is the key to project success."),
    T("Å visualisere informasjonen fra de ulike fagene er nøkkelen til å støtte samarbeidet og bygge tillit.","Visualizing the information from each discipline is the key to supporting collaboration and building trust."),
    T("Å automatisere beregningen av byggets og prosessenes ytelse korter ned latensen i å få feedback på ideer.","Automating the calculation of the building's and the process's performance cuts the latency of getting feedback on ideas."),
    T("Informasjon vurderes etter beslutningene den muliggjør – ikke etter modelldetalj («certainty of product»).","Information is judged by the decisions it enables — not by model detail (“certainty of product”).")],
  connect:T("Løfter blikket fra ett prosjekt til gjenbruk på tvers – og peker framover mot implementering i egne prosjekter.","Lifts the view from one project to reuse across projects — and points ahead to implementation in your own projects."),
  oppgaver:[
    {n:1,type:"praktisk",q:T("Hvilken informasjon bør visualiseres, integreres og automatiseres i en «Master BIM» – for tre bruksområder (1: før oppstart, 2: underveis, 3: etter bygging)?","Which information should be visualized, integrated and automated in a “Master BIM” — for three use cases (1: before start, 2: along the way, 3: after construction)?"),
      how:T("Fyll ut tabell a: tre rader (bruksområde 1–3) × tre kolonner (Visualiseres · Integreres · Automatiseres). Skriv stikkord i hver celle.","Fill in table a: three rows (use cases 1–3) × three columns (Visualized · Integrated · Automated). Write keywords in each cell."),
      svar:[T("Bruksområde 1: tomtutforming/kostnad/klima visualiseres; integreres med kalkyle","Use case 1: site layout/cost/climate visualized; integrated with cost estimating"),T("Bruksområde 2: kostnadsanalyse av endringer; mot kostnadsdatabase","Use case 2: cost analysis of changes; against a cost database"),T("Bruksområde 3: sammenligne mot byggd; automatisk oppdatert CO₂-verdi","Use case 3: compare against as-built; an automatically updated CO₂ value")],
      tool:{k:"table",title:T("Master BIM-tabell (a)","Master BIM table (a)"),prompt:T("Tre rader (bruksområde) × tre kolonner (V·I·A). Skriv stikkord i hver celle.","Three rows (use case) × three columns (V·I·A). Write keywords in each cell."),cols:[T("Bruksområde","Use case"),T("Visualiseres","Visualized"),T("Integreres","Integrated"),T("Automatiseres","Automated")],rows:[[T("1 · Før oppstart","1 · Before start"),"","",""],[T("2 · Underveis","2 · Along the way"),"","",""],[T("3 · Etter bygging","3 · After construction"),"","",""]],lockCol0:true}},
    {n:2,type:"analyse",q:T("Hvor kommer informasjonen fra, eller hvordan måler dere effekten? (Velg tabell b eller c)","Where does the information come from, or how do you measure the effect? (Choose table b or c)"),
      how:T("b) Skill hva BIM gir direkte vs. hva som hentes fra annen database (for V, I og A). c) Definer ett effektmål for hver av V, I og A.","b) Separate what BIM gives directly vs. what's pulled from another database (for V, I and A). c) Define one impact metric for each of V, I and A."),
      svar:[T("b) Tydeliggjør hva som hentes direkte fra modellen vs. eksterne kilder","b) Clarify what's pulled directly from the model vs. external sources"),T("c) Effektmål: spart tid, færre feil, raskere/sikrere beslutning","c) Impact metrics: time saved, fewer errors, faster/more confident decisions")],
      tool:{k:"table",title:T("Kilde / effekt (b eller c)","Source / impact (b or c)"),prompt:T("b) Skill modell-data fra eksterne kilder. ELLER c) definer ett effektmål per V/I/A.","b) Separate model data from external sources. OR c) define one impact metric per V/I/A."),cols:["",T("Visualisering","Visualization"),T("Integrasjon","Integration"),T("Automatisering","Automation")],rows:[[T("Fra BIM direkte","From BIM directly"),"","",""],[T("Fra annen kilde / effektmål","From another source / impact metric"),"","",""]],lockCol0:true}},
    {n:3,type:"refleksjon",q:T("Hvilken verdi kan VIA gi i deres egne prosjekter, og hvor vil dere starte?","What value can VIA bring in your own projects, and where will you start?"),
      how:T("Diskuter konkret: hvilke oppgaver dere gjør i dag kunne VIA forbedret? Velg ett realistisk startpunkt.","Discuss concretely: which tasks you do today could VIA improve? Pick one realistic starting point."),
      svar:[T("Visualisere og dokumentere byggbarhet","Visualize and document constructability"),T("Forenkle tverrfaglig tilgang til god informasjon; alternativvurdering mot kunde","Simplify cross-disciplinary access to good information; evaluate alternatives with the client"),T("Hente mengder; visualisere budsjett; kalkylemodeller","Pull quantities; visualize budget; cost models")]}
  ],
  reflect:[T("Hvor jobber vi for informasjonen i stedet for at den jobber for oss?","Where do we work for the information instead of it working for us?"),T("Hvilken automatisering ville spart mest manuelt arbeid?","Which automation would save the most manual work?"),T("Gir informasjonen et godt nok grunnlag for beslutninger (kobling til ICE)?","Does the information give a good enough basis for decisions (link to ICE)?")],
  facilitate:[T("Sikre at alle tre (V, I, A) blir berørt.","Make sure all three (V, I, A) are covered."),T("Hold fokus på «certainty of product» og beslutningene info muliggjør.","Keep the focus on “certainty of product” and the decisions information enables."),T("Knytt VIA til ICE: god informasjon er drivstoffet for gode beslutninger.","Connect VIA to ICE: good information is the fuel for good decisions.")],
  awareness:T("VIA handler om tillit: visualisering bygger tillit mellom fagene, og automatisering gir rask feedback på ideer.","VIA is about trust: visualization builds trust between disciplines, and automation gives fast feedback on ideas."),
  material:[T("Valgt kontekst","Chosen context"),T("FREYR VIA-målinger som eksempel","FREYR VIA metrics as an example"),T("VIA-triade fra forkurset","VIA triad from the pre-course"),T("Tabell-mal (a/b/c)","Table template (a/b/c)")],
  mentorTips:[T("Hold fokus på beslutningene info muliggjør – ikke modelldetaljer.","Keep the focus on the decisions information enables — not model detail."),T("Sikre at alle tre (V, I, A) berøres; grupper hopper ofte over automatisering.","Make sure all three (V, I, A) are covered; groups often skip automation."),T("Koble eksplisitt tilbake til ICE: info → beslutning.","Connect explicitly back to ICE: information → decision."),T("Pek framover mot implementering: hvilken info finnes i egne prosjekter?","Point ahead to implementation: what information already exists in your own projects?")],
  takeaway:T("Tillit er fundamentet. Visualiser for å bygge tillit; automatiser for å få rask feedback på ideene.","Trust is the foundation. Visualize to build trust; automate to get fast feedback on the ideas.") }
];

/* ---- localized views, rebuilt on language switch ---- */
let SESS, ANAT, KONTEKST;
function applyDataLang(){
  SESS = locVal(SESS_SRC);
  ANAT = locVal(ANAT_SRC);
  KONTEKST = locVal(KONTEKST_SRC);
}
applyDataLang();
