/* ============================================================
   PEDAGOGY — one deliberately different working method per session.
   Same base rhythm (1 h input · 1 h practice · 1 h reflection),
   six ways to activate 60 participants so the method itself
   reinforces what the session teaches.

   Bilingual: text leaves are wrapped in T(no,en); locVal() resolves
   PED_SRC into PED for the active language (see data.js).

   PED[no] = {
     why    : why this method fits the topic
     format : {w1:{name,ped}, w2:{name,ped}}
     w1,w2  : run-of-show [{time,met,h,p,ment,mins}]
     dd1,dd2: {do[],dont[],watch[]} tuned to the method
   }
   ============================================================ */
const PED_SRC={

/* ---------- 1 · VDC INTRO ---------- */
1:{
  why:T("Første sesjon skal bygge ett felles mentalt bilde av VDC som helhet. «1→2→4→Alle» tvinger hver av de fem til å tenke selv før noen snakker høyt – ingen gruppetenkning, alle stemmer med, og psykologisk trygghet etableres tidlig.","The first session builds one shared mental picture of VDC as a whole. “1→2→4→All” forces each of the five to think alone before anyone speaks up — no groupthink, every voice in, and psychological safety set early."),
  format:{
    w1:{name:T("1 → 2 → 4 → Alle","1 → 2 → 4 → All"),ped:T("Progressiv oppbygging: alene → par → firer/femmer. Hver deltaker har tenkt ferdig før gruppa konkluderer.","Progressive build-up: alone → pairs → four/five. Each person has finished thinking before the group concludes.")},
    w2:{name:T("Snøball-deling","Snowball sharing"),ped:T("To grupper slås sammen og sammenligner kontekstene sine før plenum – kryssbestøvning skjer før stordeling.","Two groups merge and compare their contexts before plenary — cross-pollination happens before the big share.")}
  },
  w1:[
    {time:"0–5 min",met:T("Ramme","Frame"),h:T("Sett oppgaven og formen","Set the task and the method"),p:T("Mentor viser VDC-kartet og forklarer arbeidsformen: alle tenker alene først, så par, så hele gruppa. Bekreft valgt kontekst.","The mentor shows the VDC map and explains the method: everyone thinks alone first, then in pairs, then as a group. Confirm the chosen context."),ment:T("Du: vær tydelig på at de IKKE skal diskutere ennå – det kommer.","You: be clear they should NOT discuss yet — that comes later."),mins:5},
    {time:"5–12 min",met:T("Alene (1)","Alone (1)"),h:T("Stille refleksjon","Silent reflection"),p:T("Hver deltaker skriver i stillhet: hvorfor leverer prosjekter som vårt ofte ikke godt nok? Og hvilket VDC-element kjenner jeg minst?","Each person writes in silence: why do projects like ours often fall short? And which VDC element do I know least?"),ment:T("Du: hold rommet helt stille. Ingen kommentarer, ingen lapper deles.","You: keep the room completely quiet. No comments, no notes shared."),mins:7},
    {time:"12–22 min",met:T("Par (2)","Pairs (2)"),h:T("Sammenlign to og to","Compare two by two"),p:T("Par sammenligner notatene og blir enige om de to sterkeste årsakene.","Pairs compare notes and agree on the two strongest causes."),ment:T("Du: lytt etter om de bygger på hverandre eller bare stabler meninger.","You: listen for whether they build on each other or just stack opinions."),mins:10},
    {time:"22–40 min",met:T("Femmer (4→5)","Group (4→5)"),h:T("Bygg det felles VDC-kartet","Build the shared VDC map"),p:T("Hele gruppa samler årsakene, kobler dem til 2–3 forbedringsmål og sorterer tiltak på VIA · ICE · PPM · Samspill.","The whole group gathers the causes, links them to 2–3 improvement objectives and sorts actions across VIA · ICE · PPM · Collaboration."),ment:T("Du: sjekk at alle fem har bidratt før gruppa konkluderer.","You: check that all five have contributed before the group concludes."),mins:18},
    {time:"40–52 min",met:T("Syntese","Synthesis"),h:T("Ett delbart bilde","One shareable picture"),p:T("Gruppa koker ned til ett bilde (maks 2 min) og velger presentatør.","The group boils it down to one picture (max 2 min) and picks a presenter."),ment:T("Du: be gjerne en som sjelden presenterer ta ordet i refleksjonen.","You: consider asking someone who rarely presents to speak in the reflection."),mins:12},
    {time:"52–60 min",met:T("Selvsjekk","Self-check"),h:T("Treffer vi awareness-målet?","Are we hitting the awareness goal?"),p:T("Rask runde mot awareness: ser alle VDC som en sammenheng, ikke en verktøykasse?","A quick round against the awareness goal: does everyone see VDC as a whole, not a toolbox?"),ment:T("Du: er alle med, eller henger noen igjen på ett element?","You: is everyone on board, or is someone stuck on a single element?"),mins:8}
  ],
  w2:[
    {time:"0–5 min",met:T("Ramme","Frame"),h:T("Sett rammen og kjørereglene","Set the frame and ground rules"),p:T("Mentor rammer refleksjonen og minner om at det er trygt å være uenig.","The mentor frames the reflection and reminds everyone it's safe to disagree."),ment:T("Du: etabler psykologisk trygghet før dere starter.","You: establish psychological safety before you begin."),mins:5},
    {time:"5–18 min",met:T("Snøball","Snowball"),h:T("To grupper møtes","Two groups meet"),p:T("Par av grupper sammenligner sine kontekster: hva var likt, hva var ulikt i årsakene og elementene?","Pairs of groups compare their contexts: what was alike, what differed in the causes and elements?"),ment:T("Du: be dem notere det som overrasket dem mest.","You: ask them to note what surprised them most."),mins:13},
    {time:"18–38 min",met:T("Plenum","Plenary"),h:T("Super-gruppene deler","The super-groups share"),p:T("Hver sammenslåtte gruppe deler det mest overraskende funnet for hele mentorteamet.","Each merged group shares its most surprising finding with the full mentor team."),ment:T("Du: trekk fram «helheten > delene» med deres egne eksempler.","You: bring out “the whole > the parts” using their own examples."),mins:20},
    {time:"38–50 min",met:T("Pluss/Delta","Plus/Delta"),h:T("Oppsummering og bro","Wrap-up and bridge"),p:T("Pluss/Delta + Key takeaways, og bro til plenumsdelingen på tvers av mentorteam.","Plus/Delta + key takeaways, and a bridge to the plenary share across mentor teams."),ment:T("Du: knytt det til studentenes egne prosjekter.","You: tie it to the participants' own projects."),mins:12}
  ],
  dd1:{
    do:[T("Hold den stille fasen virkelig stille – det er hele poenget.","Keep the silent phase truly silent — that's the whole point."),T("Tving fram par før firer; ingen hopper rett til gruppediskusjon.","Force pairs before the group; no one jumps straight to group discussion."),T("Sjekk at alle fem har snakket før gruppa lander.","Check that all five have spoken before the group settles."),T("Tidsbox hver fase hardt – formen faller om én fase sklir ut.","Time-box each phase hard — the method breaks if one phase slips.")],
    dont:[T("Ikke la den raskeste sette agendaen for hele gruppa.","Don't let the fastest set the agenda for the whole group."),T("Ikke gi fasitsvar – la dem bygge kartet selv.","Don't hand out the “right answer” — let them build the map themselves."),T("Ikke la én penn eie tavla gjennom hele økta.","Don't let one pen own the board the whole session."),T("Ikke la dem diskutere før de har tenkt alene.","Don't let them discuss before they've thought alone.")],
    watch:[T("Hvem snakket først i paret – og slapp den andre til?","Who spoke first in the pair — and did they let the other in?"),T("Bygger gruppa videre på parenes funn, eller starter de på nytt?","Does the group build on the pairs' findings, or start over?"),T("Energinivået ved hver overgang (alene → par → femmer).","The energy level at each transition (alone → pairs → group).")]
  },
  dd2:{
    do:[T("La super-gruppene snakke mest – du fasiliterer.","Let the super-groups talk most — you facilitate."),T("Trekk eksplisitt fram likheter og ulikheter mellom kontekstene.","Explicitly surface similarities and differences between the contexts."),T("Anerkjenn bidrag og gjør det trygt å være uenig.","Acknowledge contributions and make it safe to disagree.")],
    dont:[T("Ikke la snøballen bli to monologer – krev sammenligning.","Don't let the snowball become two monologues — demand comparison."),T("Ikke hold miniforedrag som «fasit».","Don't give mini-lectures as “the answer.”"),T("Ikke gå videre før helheten er berørt.","Don't move on before the whole has been addressed.")],
    watch:[T("Fant de noe genuint overraskende, eller bekreftet de bare hverandre?","Did they find something genuinely surprising, or just confirm each other?"),T("Kobler delingen seg til CO/PO?","Does the sharing connect to CO/PO?"),T("Tiden – hold av plass til Pluss/Delta og bro.","Time — leave room for Plus/Delta and the bridge.")]
  }
},

/* ---------- 2 · MÅLINGER ---------- */
2:{
  why:T("Vage mål er den vanligste fellen i Metrics. Gallery Walk gjør målkjedene synlige på veggen og tvinger fram ærlig peer-kritikk gjennom prikk-avstemning og feedback-lapper – studentene lærer av å sammenligne sin egen kjede med fire andres.","Vague objectives are the most common trap in Metrics. A gallery walk puts the objective chains on the wall and forces honest peer critique through dot-voting and feedback notes — people learn by comparing their own chain with four others."),
  format:{
    w1:{name:T("Bygg måltavla","Build the metrics board"),ped:T("Gruppa bygger hele kjeden – synergi/konflikt → produksjonsmåling → kontrollerbar faktor – på én lesbar tavle.","The group builds the whole chain — synergy/conflict → production metric → controllable factor — on one readable board.")},
    w2:{name:T("Gallery Walk + prikk-avstemning","Gallery walk + dot-voting"),ped:T("Alle vandrer mellom tavlene, prikker den mest vanntette målkjeden og henger feedback på den vageste.","Everyone walks between the boards, dots the most watertight chain and posts feedback on the vaguest.")}
  },
  w1:[
    {time:"0–5 min",met:T("Ramme","Frame"),h:T("Sett oppgaven","Set the task"),p:T("Mentor rammer oppgaven og minner om regelen: en måling uten tall og enhet er bare et ønske.","The mentor frames the task and repeats the rule: a metric with no number and unit is just a wish."),ment:T("Du: gjenta «du styrer det du måler».","You: repeat “you manage what you measure.”"),mins:5},
    {time:"5–10 min",met:T("Stille start","Silent start"),h:T("Hva kan faktisk måles?","What can actually be measured?"),p:T("Hver deltaker noterer i stillhet hvilke av forbedringsmålene som faktisk lar seg tallfeste.","Each person notes in silence which improvement objectives can actually be quantified."),ment:T("Du: hold det kort og stille.","You: keep it short and quiet."),mins:5},
    {time:"10–45 min",met:T("Bygg","Build"),h:T("Bygg hele målkjeden","Build the full chain"),p:T("Gruppa bygger tavla: synergi/konflikt-kart → produksjonsmålinger (med enhet) → kontrollerbare faktorer.","The group builds the board: synergy/conflict map → production metrics (with units) → controllable factors."),ment:T("Du: sirkulér og spør «hva er enheten?» hver gang noe er vagt.","You: circulate and ask “what's the unit?” every time something is vague."),mins:35},
    {time:"45–55 min",met:T("Skjerp","Sharpen"),h:T("Gjør den målbar","Make it measurable"),p:T("Gruppa bytter ut alle vage ord med tall + enhet, og skiller utfall fra handling.","The group swaps every vague word for a number + unit, and separates outcome from action."),ment:T("Du: utfordre «bedre kvalitet» – be om hvordan det måles.","You: challenge “better quality” — ask how it's measured."),mins:10},
    {time:"55–60 min",met:T("Heng opp","Post it"),h:T("Klargjør for galleriet","Ready for the gallery"),p:T("Tavla henges opp så den kan leses på to meters avstand.","The board goes up so it can be read from two meters away."),ment:T("Du: er tavla lesbar utenfra? Hvis ikke – for mye tekst.","You: is the board readable from a distance? If not — too much text."),mins:5}
  ],
  w2:[
    {time:"0–5 min",met:T("Ramme","Frame"),h:T("Hva kjennetegner en god måling?","What makes a good metric?"),p:T("Mentor setter kriteriene før vandringen: målbar, koblet til kundemål, skiller utfall fra handling.","The mentor sets the criteria before the walk: measurable, tied to Client Objectives, separates outcome from action."),ment:T("Du: gi hver deltaker 2 grønne prikker og 1 feedback-lapp.","You: give each person 2 green dots and 1 feedback note."),mins:5},
    {time:"5–25 min",met:T("Gallery Walk","Gallery walk"),h:T("Vandre, prikk, gi feedback","Walk, dot, give feedback"),p:T("Alle går rundt til de andre gruppenes tavler, prikker den mest vanntette målkjeden og henger en feedback-lapp på den vageste.","Everyone walks to the other groups' boards, dots the most watertight chain and posts a feedback note on the vaguest."),ment:T("Du: hold dem i bevegelse – maks 3–4 min per tavle.","You: keep them moving — max 3–4 min per board."),mins:20},
    {time:"25–42 min",met:T("Forsvar","Defend"),h:T("Stopp ved 2–3 tavler","Stop at 2–3 boards"),p:T("Gruppene forsvarer valgene sine der det er flest prikker eller flest spørsmål. Utfall vs. handling i fokus.","Groups defend their choices where there are the most dots or the most questions. Outcome vs. action in focus."),ment:T("Du: la gruppa svare på feedbacken – ikke svar for dem.","You: let the group answer the feedback — don't answer for them."),mins:17},
    {time:"42–50 min",met:T("Pluss/Delta","Plus/Delta"),h:T("Oppsummering og bro","Wrap-up and bridge"),p:T("Pluss/Delta + Key takeaways, og bro til plenum.","Plus/Delta + key takeaways, and a bridge to plenary."),ment:T("Du: knytt kjeden tilbake til kundens hvorfor (CO).","You: tie the chain back to the client's why (CO)."),mins:8}
  ],
  dd1:{
    do:[T("Krev tall og enhet på hver eneste måling.","Require a number and a unit on every single metric."),T("Tving fram skillet produksjonsmåling (utfall) vs. kontrollerbar faktor (handling).","Force the distinction: production metric (outcome) vs. controllable factor (action)."),T("Sørg for at tavla kan leses på to meters avstand – det er en gallerivegg.","Make sure the board reads from two meters — it's a gallery wall.")],
    dont:[T("Ikke godta «bedre kvalitet» eller «mindre feil» uten en måleenhet.","Don't accept “better quality” or “fewer errors” without a unit of measure."),T("Ikke la dem måle alt – tving fram prioritering.","Don't let them measure everything — force prioritization."),T("Ikke fyll tavla med tekst; det er en plakat, ikke et dokument.","Don't fill the board with text; it's a poster, not a document.")],
    watch:[T("Henger kjeden faktisk sammen fra kundemål helt ned til en kontrollerbar faktor?","Does the chain actually connect from Client Objective down to a controllable factor?"),T("Er målingene ærlige, eller ønsketenkning i tallform?","Are the metrics honest, or wishful thinking in numbers?"),T("Klarer gruppa å forklare HVORFOR de måler nettopp dette?","Can the group explain WHY they measure this in particular?")]
  },
  dd2:{
    do:[T("Hold deltakerne i bevegelse – galleriet dør om de setter seg.","Keep people moving — the gallery dies if they sit down."),T("La gruppene forsvare egne valg mot feedbacken.","Let groups defend their own choices against the feedback."),T("Løft fram den klareste OG den vageste kjeden – begge lærer bort.","Hold up both the clearest AND the vaguest chain — both teach.")],
    dont:[T("Ikke la prikkingen bli en popularitetskonkurranse – minn om kriteriene.","Don't let the dotting become a popularity contest — remind them of the criteria."),T("Ikke ranger gruppene; pek på mønstre.","Don't rank the groups; point to patterns."),T("Ikke hopp over forsvarsrunden – det er der innsikten sitter.","Don't skip the defense round — that's where the insight lives.")],
    watch:[T("Prikker de etter kriteriene, eller etter hvem de liker?","Are they dotting by the criteria, or by who they like?"),T("Tar gruppene feedbacken inn, eller forsvarer de seg defensivt?","Do groups take the feedback in, or get defensive?"),T("Ser de forskjellen på en måling og et ønske nå?","Do they see the difference between a metric and a wish now?")]
  }
},

/* ---------- 3 · ICE ---------- */
3:{
  why:T("ICE handler om beslutninger i sanntid med alle fag i rommet – det kan ikke forelesere bort, det må erfares. Rolle-simulering lar gruppa kjenne latensen kollapse på kroppen, og etterpå brukes en strukturert «after-action review» til å hente ut hvorfor det fungerte.","ICE is about real-time decisions with every discipline in the room — you can't lecture it, you have to feel it. Role simulation lets the group feel the latency collapse, then a structured after-action review pulls out why it worked."),
  format:{
    w1:{name:T("Rolle-simulering","Role simulation"),ped:T("Gruppa planlegger og kjører en ekte ICE-sesjon i sanntid, med fordelte fagroller og klokka i gang.","The group plans and runs a real ICE session in real time, with assigned discipline roles and the clock running.")},
    w2:{name:T("After-action review","After-action review"),ped:T("Strukturert debrief: hva forventet vi → hva skjedde → hvorfor → hva nå. Erfaringen gjøres til innsikt.","A structured debrief: what did we expect → what happened → why → what now. Experience becomes insight.")}
  },
  w1:[
    {time:"0–5 min",met:T("Ramme","Frame"),h:T("Sett oppgaven","Set the task"),p:T("Mentor rammer oppgaven og minner om at ICE er for de gjensidige problemene – ikke det sekvensielle.","The mentor frames the task and reminds them ICE is for reciprocal problems — not sequential ones."),ment:T("Du: be dem velge noe to fag MÅ løse sammen.","You: ask them to pick something two disciplines MUST solve together."),mins:5},
    {time:"5–15 min",met:T("Planlegg","Plan"),h:T("Planlegg sesjonen","Plan the session"),p:T("Gruppa velger beslutningsspørsmål, fordeler fagroller og avklarer underlag og agenda (ICE-planleggeren).","The group picks the decision question, assigns roles and clarifies inputs and agenda (the ICE planner)."),ment:T("Du: sjekk at de inviterer dem som eier konsekvensene.","You: check that they invite the people who own the consequences."),mins:10},
    {time:"15–40 min",met:T("Simulering","Simulation"),h:T("Kjør ICE i sanntid","Run ICE in real time"),p:T("Gruppa kjører den fasede ICE-simuleringen: hensikt → gjennomgang → beslutning → ansvar. Klokka styrer.","The group runs the phased ICE simulation: purpose → review → decision → responsibility. The clock runs it."),ment:T("Du: hold tempo, tving fram en faktisk beslutning.","You: keep the pace, force an actual decision."),mins:25},
    {time:"40–50 min",met:T("Mål","Measure"),h:T("Var sesjonen vellykket?","Was the session a success?"),p:T("Gruppa definerer målinger for under, rett etter og en måned etter.","The group defines metrics for during, right after and one month later."),ment:T("Du: knytt til FREYR/Aurora-eksemplene.","You: connect to the FREYR/Aurora examples."),mins:10},
    {time:"50–60 min",met:T("Klargjør","Prepare"),h:T("Forbered deling","Prepare to share"),p:T("Gruppa noterer beslutningen og hva som overrasket dem ved å beslutte i sanntid.","The group notes the decision and what surprised them about deciding in real time."),ment:T("Du: be dem huske beslutningsøyeblikket – det skal deles.","You: ask them to remember the moment of decision — it gets shared."),mins:10}
  ],
  w2:[
    {time:"0–5 min",met:T("Ramme","Frame"),h:T("Debrief-reglene","Debrief rules"),p:T("Mentor setter after-action-rammen: vi dømmer ikke beslutningen, vi forstår prosessen.","The mentor sets the after-action frame: we don't judge the decision, we understand the process."),ment:T("Du: gjør det trygt å si «vi somlet her».","You: make it safe to say “we dragged our feet here.”"),mins:5},
    {time:"5–22 min",met:T("Hva skjedde","What happened"),h:T("Hver gruppe gjenforteller","Each group retells"),p:T("Hver gruppe beskriver sitt beslutningsøyeblikk (2–3 min): hva forventet dere, hva skjedde faktisk?","Each group describes its moment of decision (2–3 min): what did you expect, what actually happened?"),ment:T("Du: hold dem på prosessen, ikke fagdetaljene.","You: keep them on the process, not the technical details."),mins:17},
    {time:"22–40 min",met:T("Hvorfor","Why"),h:T("Hva drev tempoet?","What drove the pace?"),p:T("Fasilitert: hva gjorde beslutningen rask og trygg? Hvor satt latensen? Hva ville stoppet en ekte økt?","Facilitated: what made the decision fast and confident? Where did latency sit? What would stall a real session?"),ment:T("Du: still spørsmålene, la dem svare – snakk minst mulig.","You: ask the questions, let them answer — talk as little as possible."),mins:18},
    {time:"40–50 min",met:T("Bro","Bridge"),h:T("Hva nå?","What now?"),p:T("Koble til Aurora 2 (gjensidig arbeid ga målbart bedre resultat) og egne prosjekter.","Connect to Aurora 2 (reciprocal work produced measurably better results) and their own projects."),ment:T("Du: «hvor i ditt prosjekt finnes et gjensidig problem?»","You: “where in your project is there a reciprocal problem?”"),mins:10}
  ],
  dd1:{
    do:[T("Sørg for at problemet er gjensidig – minst to fag må løse det sammen.","Make sure the problem is reciprocal — at least two disciplines must solve it together."),T("Hold tempo i simuleringen; tving fram en faktisk beslutning før tiden er ute.","Keep the pace in the simulation; force an actual decision before time runs out."),T("La en i gruppa ta fasilitatorrollen og styre fasene.","Let someone in the group take the facilitator role and drive the phases.")],
    dont:[T("Ikke la dem velge et sekvensielt problem – da forsvinner poenget.","Don't let them pick a sequential problem — the point disappears."),T("Ikke la simuleringen bli et statusmøte uten beslutning.","Don't let the simulation become a status meeting with no decision."),T("Ikke grip inn og løs det for dem når det butter.","Don't step in and solve it for them when it gets stuck.")],
    watch:[T("Hvem tar fasilitatorrollen (SPGR: Kontroll)?","Who takes the facilitator role (SPGR: Control)?"),T("Kommer de faktisk fram til en beslutning, eller utsetter de?","Do they actually reach a decision, or defer it?"),T("Merker de selv hvor mye ventetid de nettopp hoppet over?","Do they notice how much waiting they just skipped?")]
  },
  dd2:{
    do:[T("Hold debriefen på prosessen: hva skjedde og hvorfor, ikke fagfasiten.","Keep the debrief on the process: what happened and why, not the technical answer."),T("Få fram latens-poenget med deres egne tall.","Bring out the latency point with their own numbers."),T("Anerkjenn at det er trygt å si hva som gikk tregt.","Acknowledge that it's safe to say what went slowly.")],
    dont:[T("Ikke la debriefen bli fire monologer om hva de bestemte.","Don't let the debrief become four monologues about what they decided."),T("Ikke døm om beslutningen var «riktig».","Don't judge whether the decision was “right.”"),T("Ikke gå videre uten å koble til et ekte prosjekt.","Don't move on without connecting to a real project.")],
    watch:[T("Skiller de prosessen (hvordan) fra innholdet (hva)?","Do they separate the process (how) from the content (what)?"),T("Ser de forskjellen på sekvensiell og gjensidig flyt nå?","Do they see the difference between sequential and reciprocal flow now?"),T("Klarer de å peke på et gjensidig problem i eget prosjekt?","Can they point to a reciprocal problem in their own project?")]
  }
},

/* ---------- 4 · PPM PROSESSMAPPING ---------- */
4:{
  why:T("Prosessforståelse er konstruktivistisk – man ser sløsingen først når man fysisk legger ut steg, køer og lager. En kort «speed-kritikk», der én utsending besøker nabogruppa, gjør at de oppdager skjulte køer hos hverandre, raskt og gjensidig.","Process understanding is constructivist — you only see the waste once you physically lay out steps, queues and inventory. A short “speed critique,” where one emissary visits the neighboring group, surfaces hidden queues in each other's maps, fast and mutual."),
  format:{
    w1:{name:T("Hands-on bygging + speed-kritikk","Hands-on build + speed critique"),ped:T("Gruppa bygger prosesskartet i svømmebaner. En utsending besøker nabogruppa og peker på skjulte køer.","The group builds the process map in swimlanes. An emissary visits the neighboring group and points out hidden queues.")},
    w2:{name:T("Forbedrings-sprint","Improvement sprint"),ped:T("Gruppene optimaliserer kartet live – fjerner køer, slår sammen steg – og måler gjennomløpstid før/etter.","Groups optimize the map live — remove queues, merge steps — and measure lead time before/after.")}
  },
  w1:[
    {time:"0–5 min",met:T("Ramme","Frame"),h:T("Vis et ekte eksempel","Show a real example"),p:T("Mentor viser Heathrow-armeringen (30→5 dager) og rammer oppgaven: et prosjekt er et produksjonssystem.","The mentor shows the Heathrow rebar case (30 → 5 days) and frames the task: a project is a production system."),ment:T("Du: bruk eksempelet som mal når noen står fast.","You: use the example as a model when someone is stuck."),mins:5},
    {time:"5–12 min",met:T("Spore","Spot"),h:T("Hvor er kø og lager?","Where are queues and inventory?"),p:T("Gruppa gir to konkrete eksempler på kø og to på lager (WIP) før de bygger.","The group gives two concrete examples of queues and two of inventory (WIP) before building."),ment:T("Du: de overser nesten alltid venting – press på det.","You: they almost always overlook waiting — push on it."),mins:7},
    {time:"12–45 min",met:T("Bygg","Build"),h:T("Bygg prosesskartet","Build the process map"),p:T("Gruppa legger ett kort per steg i svømmebaner, med symboler: oppgave / kø / lager / flyt.","The group places one card per step in swimlanes, with symbols: task / queue / inventory / flow."),ment:T("Du: sirkulér og spør «hva skjer mellom disse to stegene?»","You: circulate and ask “what happens between these two steps?”"),mins:33},
    {time:"45–55 min",met:T("Speed-kritikk","Speed critique"),h:T("Besøk nabogruppa","Visit the neighbor"),p:T("Én utsending fra hver gruppe besøker nabogruppa i 5 min og peker på minst én skjult kø.","One emissary from each group visits the neighboring group for 5 min and points out at least one hidden queue."),ment:T("Du: koordiner byttet, hold det til 5 min.","You: coordinate the swap, keep it to 5 min."),mins:10},
    {time:"55–60 min",met:T("Juster","Adjust"),h:T("Ta inn kritikken","Take in the critique"),p:T("Gruppa justerer eget kart ut fra det utsendingen tok med tilbake.","The group adjusts its map based on what the emissary brought back."),ment:T("Du: ble en skjult kø synlig nå?","You: did a hidden queue become visible now?"),mins:5}
  ],
  w2:[
    {time:"0–5 min",met:T("Ramme","Frame"),h:T("Sett sprinten","Set the sprint"),p:T("Mentor rammer forbedrings-sprinten: behold flyten, kutt køene.","The mentor frames the improvement sprint: keep the flow, cut the queues."),ment:T("Du: minn om flyt- vs. ressurseffektivitet.","You: remind them of flow vs. resource efficiency."),mins:5},
    {time:"5–25 min",met:T("Optimaliser","Optimize"),h:T("Bygg det forbedrede kartet","Build the improved map"),p:T("Gruppa kopierer kartet og lager en optimalisert versjon: fjern en kø, slå sammen steg, endre rekkefølge.","The group copies the map and builds an optimized version: remove a queue, merge steps, change order."),ment:T("Du: utfordre «alle må være travle»-tankegangen.","You: challenge the “everyone must be busy” mindset."),mins:20},
    {time:"25–42 min",met:T("Mål","Measure"),h:T("Før vs. etter på tvers","Before vs. after, across groups"),p:T("Gruppene sammenligner gjennomløpstid før og etter, og deler det mest effektive grepet.","Groups compare lead time before and after, and share the single most effective move."),ment:T("Du: be om tall – hvor mange dager spart?","You: ask for numbers — how many days saved?"),mins:17},
    {time:"42–50 min",met:T("Bro","Bridge"),h:T("Oppsummering","Wrap-up"),p:T("Flyt- vs. ressurseffektivitet; bro til variabilitet-sesjonen.","Flow vs. resource efficiency; bridge to the variability session."),ment:T("Du: pek framover mot terningspillet.","You: point ahead to the dice game."),mins:8}
  ],
  dd1:{
    do:[T("Hjelp dem å SE køene – pek på mellomrommene mellom steg.","Help them SEE the queues — point to the gaps between steps."),T("Hold speed-kritikken til 5 min og til ÉN skjult kø.","Keep the speed critique to 5 min and to ONE hidden queue."),T("Sørg for at kø og lager får egne symboler, ikke bare piler.","Make sure queues and inventory get their own symbols, not just arrows.")],
    dont:[T("Ikke la dem tegne en pen Gantt – det er flyt, ikke en tidslinje.","Don't let them draw a neat Gantt — this is flow, not a timeline."),T("Ikke la utsendingen bli sittende hos nabogruppa.","Don't let the emissary settle in at the neighboring group."),T("Ikke godta et kart uten en eneste kø – den finnes alltid.","Don't accept a map without a single queue — there's always one.")],
    watch:[T("Ser de venting og lager, eller bare arbeidsoppgaver?","Do they see waiting and inventory, or just tasks?"),T("Tar gruppa imot nabogruppas kritikk?","Does the group take in the neighbor's critique?"),T("Skjønner de at travle ressurser ikke er det samme som flyt?","Do they grasp that busy resources aren't the same as flow?")]
  },
  dd2:{
    do:[T("Krev tall på gjennomløpstid før og etter.","Require numbers on lead time before and after."),T("Få fram det billigste grepet, ikke det mest avanserte.","Bring out the cheapest move, not the most advanced one."),T("Koble forbedringen til en kontrollerbar faktor.","Connect the improvement to a controllable factor.")],
    dont:[T("Ikke la sprinten bli en total omskriving – ett eller to grep holder.","Don't let the sprint become a total rewrite — one or two moves is enough."),T("Ikke godta «det føles raskere» uten måling.","Don't accept “it feels faster” without a measurement."),T("Ikke hopp over sammenligningen på tvers.","Don't skip the cross-group comparison.")],
    watch:[T("Klarte de å korte ned gjennomløpstiden – og vise det?","Did they shorten the lead time — and show it?"),T("Forstår de hvorfor færre køer gir mer forutsigbar flyt?","Do they understand why fewer queues give more predictable flow?"),T("Ser de koblingen til egne prosjekter?","Do they see the link to their own projects?")]
  }
},

/* ---------- 5 · PPM VARIABILITET ---------- */
5:{
  why:T("Variabilitet er kontraintuitivt – et spill gjør det fysisk merkbart. Vi følger Kolbs erfaringssirkel: spill → observer tallene → reflekter → generaliser til eget prosjekt. Dette er ukas mest lekne sesjon, helt bevisst – energien er en del av læringen.","Variability is counterintuitive — a game makes it physically obvious. We follow Kolb's experiential cycle: play → observe the numbers → reflect → generalize to your own project. This is the week's most playful session, on purpose — the energy is part of the learning."),
  format:{
    w1:{name:T("Spillbasert læring","Game-based learning"),ped:T("Gruppa spiller terningspillet og Push/Pull, og samler rene observasjoner – ingen konklusjoner ennå.","The group plays the dice game and Push/Pull, gathering clean observations — no conclusions yet.")},
    w2:{name:T("Fra spill til virkelighet","From game to reality"),ped:T("Kolb-generalisering: koble det de SÅ i spillet til konkrete situasjoner i egne prosjekter.","Kolb generalization: connect what they SAW in the game to concrete situations in their own projects.")}
  },
  w1:[
    {time:"0–5 min",met:T("Ramme","Frame"),h:T("Vi spiller – ikke foreleser","We play — we don't lecture"),p:T("Mentor rammer kort: ingen teori nå, vi spiller og observerer.","The mentor frames it briefly: no theory now, we play and observe."),ment:T("Du: motstå trangen til å forklare poenget på forhånd.","You: resist the urge to explain the point in advance."),mins:5},
    {time:"5–25 min",met:T("Terningspill","Dice game"),h:T("Kjør med variabilitet","Run with variability"),p:T("Gruppa kjører terningspillet med høy variabilitet og store batcher, og måler kø og gjennomløp.","The group runs the dice game with high variability and large batches, measuring queues and throughput."),ment:T("Du: la spillet snakke – pek bare på tallene.","You: let the game speak — just point to the numbers."),mins:20},
    {time:"25–45 min",met:T("Push/Pull","Push/Pull"),h:T("Kjør begge måtene","Run both ways"),p:T("Gruppa kjører Push vs Pull og sammenligner ferdige enheter og lager mellom stasjonene.","The group runs Push vs Pull and compares finished units and inventory between stations."),ment:T("Du: sørg for at begge kjøres, så forskjellen blir tydelig.","You: make sure both are run, so the difference is clear."),mins:20},
    {time:"45–60 min",met:T("Observer","Observe"),h:T("Hva SKJEDDE?","What HAPPENED?"),p:T("Gruppa noterer rene observasjoner fra spillene – tall og fakta, ikke tolkninger ennå.","The group notes clean observations from the games — numbers and facts, not interpretations yet."),ment:T("Du: stopp dem hvis de konkluderer for tidlig.","You: stop them if they conclude too early."),mins:15}
  ],
  w2:[
    {time:"0–5 min",met:T("Ramme","Frame"),h:T("Fra spill til prosjekt","From game to project"),p:T("Mentor rammer generaliseringen: hva betydde det vi så?","The mentor frames the generalization: what did what we saw mean?"),ment:T("Du: minn om at variabilitet rammer hele systemet.","You: remind them that variability hits the whole system."),mins:5},
    {time:"5–20 min",met:T("Observasjon","Observation"),h:T("Én tallfestet observasjon","One numeric observation"),p:T("Hver gruppe deler én konkret observasjon fra spillet (f.eks. kølengde ved høy variabilitet).","Each group shares one concrete observation from the game (e.g. queue length at high variability)."),ment:T("Du: hold dem til tall, ikke synsing.","You: hold them to numbers, not opinions."),mins:15},
    {time:"20–40 min",met:T("Generaliser","Generalize"),h:T("Hvor kjenner dere det igjen?","Where do you recognize it?"),p:T("Par-deling: hvor i EGET prosjekt skjer akkurat dette? Hva er den billigste dempingen?","Pair sharing: where in YOUR project does exactly this happen? What's the cheapest way to dampen it?"),ment:T("Du: bruk energien (SPGR: Omsorg) – dette er lekent.","You: use the energy (SPGR: Nurture) — this is playful."),mins:20},
    {time:"40–50 min",met:T("Bro","Bridge"),h:T("Tiltak og bro","Actions and bridge"),p:T("Koble til prosesskartet fra forrige sesjon: hvor vil dere dempe variabilitet?","Connect to the process map from the previous session: where would you dampen variability?"),ment:T("Du: knytt følelsen i spillet til ekte erfaring.","You: connect the feel of the game to real experience."),mins:10}
  ],
  dd1:{
    do:[T("La spillet snakke – ikke foreles poenget på forhånd.","Let the game speak — don't lecture the point in advance."),T("Sørg for at begge runder/måter måles, så kontrasten blir tydelig.","Make sure both rounds/ways are measured, so the contrast is clear."),T("Hold stemningen høy – dette skal være gøy.","Keep the energy high — this should be fun.")],
    dont:[T("Ikke avslør konklusjonen før de har sett den selv.","Don't reveal the conclusion before they've seen it themselves."),T("Ikke la dem konkludere før observasjonsfasen.","Don't let them conclude before the observation phase."),T("Ikke hopp over å notere tallene – de trengs i refleksjonen.","Don't skip noting the numbers — they're needed in the reflection.")],
    watch:[T("Ser de at køer bygger seg opp selv med lik snittkapasitet?","Do they see queues build up even with equal average capacity?"),T("Holder de observasjon og tolkning fra hverandre?","Do they keep observation and interpretation apart?"),T("Energinivå – får alle fem være med å spille?","Energy level — does everyone get to play?")]
  },
  dd2:{
    do:[T("Hold dem til tallfestede observasjoner i starten.","Hold them to numeric observations at the start."),T("Få dem til å koble spillet til en konkret situasjon i eget prosjekt.","Get them to connect the game to a concrete situation in their own project."),T("Trekk fram den billigste måten å dempe variabilitet på.","Bring out the cheapest way to dampen variability.")],
    dont:[T("Ikke la refleksjonen bli abstrakt «flyt er viktig»-prat.","Don't let the reflection become abstract “flow is important” talk."),T("Ikke godta gjenkjenning uten et konkret eksempel.","Don't accept recognition without a concrete example."),T("Ikke glem broen tilbake til prosesskartet.","Don't forget the bridge back to the process map.")],
    watch:[T("Klarer de å oversette spillet til egen hverdag?","Can they translate the game to their own day-to-day?"),T("Forstår de at «alle travle» ikke er god flyt?","Do they understand that “everyone busy” isn't good flow?"),T("Hvilket grep velger de – og er det realistisk?","Which move do they choose — and is it realistic?")]
  }
},

/* ---------- 6 · VIA ---------- */
6:{
  why:T("Siste sesjon løfter blikket fra ett prosjekt til gjenbruk på tvers, og peker framover mot implementering. World Café – roterende bord der en vert blir igjen og resten flytter seg – krysser ideer mellom alle fire gruppene og ender i en felles «harvest». Perfekt for «hvor starter VIA i MITT prosjekt?».","The last session lifts the view from one project to reuse across projects, and points ahead to implementation. World Café — rotating tables where one host stays and the rest move on — crosses ideas between all four groups and ends in a shared “harvest.” Perfect for “where does VIA start in MY project?”"),
  format:{
    w1:{name:T("Bygg Master-BIM","Build the Master BIM"),ped:T("Gruppa fyller Master-BIM-tabellene (V·I·A × tre bruksområder) og kobler informasjon til beslutninger.","The group fills the Master BIM tables (V·I·A × three use cases) and links information to decisions.")},
    w2:{name:T("World Café","World Café"),ped:T("Roterende bord: gruppene flytter seg og bygger videre på det forrige gruppe skrev. En vert blir igjen ved hvert bord.","Rotating tables: groups move and build on what the previous group wrote. One host stays at each table.")}
  },
  w1:[
    {time:"0–5 min",met:T("Ramme","Frame"),h:T("Sett oppgaven","Set the task"),p:T("Mentor rammer VIA som de tre bruksområdene for BIM/informasjon, og minner om «certainty of product».","The mentor frames VIA as the three use cases for BIM/information, and reminds them of “certainty of product.”"),ment:T("Du: hold fokus på beslutningene info muliggjør – ikke modelldetaljer.","You: keep the focus on the decisions information enables — not model detail."),mins:5},
    {time:"5–40 min",met:T("Bygg","Build"),h:T("Fyll Master-BIM","Fill the Master BIM"),p:T("Gruppa fyller tabellen: tre bruksområder (før / underveis / etter) × Visualiseres · Integreres · Automatiseres, og kilde/effekt.","The group fills the table: three use cases (before / during / after) × Visualized · Integrated · Automated, plus source/impact."),ment:T("Du: sikre at alle tre – V, I og A – blir berørt; automatisering glemmes ofte.","You: make sure all three — V, I and A — are covered; automation gets forgotten."),mins:35},
    {time:"40–55 min",met:T("Koble","Connect"),h:T("Hva muliggjør dette?","What does this enable?"),p:T("For hver rad: hvilken beslutning gjør denne informasjonen bedre? (kobling til ICE).","For each row: which decision does this information make better? (link to ICE)."),ment:T("Du: «info → beslutning» – gjør koblingen eksplisitt.","You: “information → decision” — make the link explicit."),mins:15},
    {time:"55–60 min",met:T("Velg vert","Pick a host"),h:T("Klargjør café-en","Ready the café"),p:T("Gruppa velger én «vert» som blir igjen ved bordet i refleksjonen.","The group picks one “host” who stays at the table during the reflection."),ment:T("Du: forklar café-reglene før dere bytter rom.","You: explain the café rules before you switch rooms."),mins:5}
  ],
  w2:[
    {time:"0–5 min",met:T("Ramme","Frame"),h:T("Café-reglene","Café rules"),p:T("Mentor setter World Café-rammen: verten blir, resten roterer, hver gruppe bygger videre på det forrige skrev.","The mentor sets the World Café frame: the host stays, the rest rotate, each group builds on what the previous one wrote."),ment:T("Du: gjør det tydelig hvilket bord hver gruppe starter ved.","You: make it clear which table each group starts at."),mins:5},
    {time:"5–35 min",met:T("Roter","Rotate"),h:T("To–tre runder ved bordene","Two or three rounds at the tables"),p:T("Gruppene roterer mellom bordene. Spørsmål per bord: hvor starter VIA i ditt prosjekt? Bygg videre på forrige gruppes svar.","Groups rotate between tables. Question per table: where does VIA start in your project? Build on the previous group's answers."),ment:T("Du: hold tiden per runde (8–10 min) og sett rotasjonen i gang.","You: keep time per round (8–10 min) and start the rotation."),mins:30},
    {time:"35–48 min",met:T("Harvest","Harvest"),h:T("Vertene oppsummerer","The hosts summarize"),p:T("Hver vert oppsummerer hva bordet endte på. Felles tema trekkes fram: certainty of product.","Each host summarizes where the table landed. A shared theme emerges: certainty of product."),ment:T("Du: la vertene snakke; samle mønstrene.","You: let the hosts talk; gather the patterns."),mins:13},
    {time:"48–60 min",met:T("Bro","Bridge"),h:T("Bro til implementering","Bridge to implementation"),p:T("Koble til implementeringsfasen: hvilken info finnes allerede i egne prosjekter?","Connect to the implementation phase: what information already exists in your own projects?"),ment:T("Du: pek framover mot fredagens implementeringsplan.","You: point ahead to Friday's implementation plan."),mins:12}
  ],
  dd1:{
    do:[T("Hold fokus på beslutningene informasjonen muliggjør, ikke modelldetaljer.","Keep the focus on the decisions information enables, not model detail."),T("Sikre at alle tre – V, I og A – berøres; grupper hopper ofte over automatisering.","Make sure all three — V, I and A — are covered; groups often skip automation."),T("Koble eksplisitt tilbake til ICE: info er drivstoffet for beslutninger.","Connect explicitly back to ICE: information is the fuel for decisions.")],
    dont:[T("Ikke la dem havne i en diskusjon om modell-LOD og detaljnivå.","Don't let them slide into a debate about model LOD and detail level."),T("Ikke godta en tabell der A-kolonnen står tom.","Don't accept a table where the A column is empty."),T("Ikke mist «certainty of product» av syne.","Don't lose sight of “certainty of product.”")],
    watch:[T("Vurderer de info etter beslutningene den gir, eller etter detaljgrad?","Do they judge information by the decisions it gives, or by detail level?"),T("Er alle tre bruksområdene dekket?","Are all three use cases covered?"),T("Ser de koblingen VIA → ICE?","Do they see the VIA → ICE link?")]
  },
  dd2:{
    do:[T("Hold rotasjonen i gang – verten blir, resten flytter seg.","Keep the rotation moving — the host stays, the rest move on."),T("Be hver gruppe bygge VIDERE på det forrige skrev, ikke starte på nytt.","Ask each group to build ON what the previous one wrote, not start over."),T("La vertene eie oppsummeringen i harvesten.","Let the hosts own the summary in the harvest.")],
    dont:[T("Ikke la et bord starte blankt hver runde – poenget er å bygge lag på lag.","Don't let a table start blank each round — the point is to build layer on layer."),T("Ikke la verten bli passiv – verten loser de nye inn i samtalen.","Don't let the host go passive — the host guides newcomers into the conversation."),T("Ikke avslutt uten broen til implementering.","Don't finish without the bridge to implementation.")],
    watch:[T("Bygger ideene seg oppover runde for runde?","Do the ideas build up round by round?"),T("Får alle bordene besøk, eller klumper det seg?","Do all tables get visited, or does it bunch up?"),T("Har hver student et realistisk førstesteg for eget prosjekt?","Does each person have a realistic first step for their own project?")]
  }
}
};

/* ---- localized pedagogy, rebuilt on language switch ---- */
let PED;
function applyPedLang(){ PED = locVal(PED_SRC); }
applyPedLang();
